"""Catalog-expansion seed — paste into build_lookups.py PRODUCTS list."""

CATALOG_EXPANSION_2026_05 = [
    ('ARC Travel Intelligence', 'Airlines Reporting Corporation', 'investigative_data', 0, 0, None,
     "ARC's Travel Intelligence Program provides commercial air travel data analytics used for law-enforcement and investigative work.",
     ['Airlines Reporting Corporation Travel Intelligence Program', 'ARC Travel Intelligence Program', 'ARC TIP']),
    ('AWS Translate', 'Amazon Web Services', 'translation', 1, 0, None,
     "Amazon's neural machine translation service for translating text between languages.",
     ['AWS Translate', 'Amazon Translate']),
    ('Amazon Alexa', 'Amazon', 'nlp', 0, 0, None,
     "Amazon's voice assistant platform supporting custom skills and voice-driven applications.",
     ['Amazon Alexa', 'Alexa', 'Amazon Alexa Skill', 'Alexa Skill']),
    ('Amazon Connect', 'Amazon Web Services', 'nlp', 1, 0, None,
     'AWS cloud contact center with built-in AI for IVR, transcription, sentiment, and agent assist.',
     ['Amazon Connect', 'AWS Connect']),
    ('Aretec EDP', 'Aretec', 'data_analytics', 0, 0, None,
     'Aretec-built Enterprise Data Platform used at the SEC for analytics and ML workloads, distinct from NEAT.',
     ['Aretec EDP', 'EDP', 'SEC EDP', 'Enterprise Data Platform (Aretec)']),
    ('Aretec SEARCH', 'Aretec', 'search', 0, 0, None,
     'Aretec-built SEARCH platform used at the SEC for full-text and analytical search across regulatory filings; sibling to NEAT and EDP.',
     ['Aretec SEARCH', 'SEARCH', 'SEC SEARCH']),
    ('AttackIQ', 'AttackIQ', 'security_tool', 0, 0, None,
     'Breach-and-attack-simulation platform that uses ML to validate security controls against MITRE ATT&CK techniques.',
     ['AttackIQ']),
    ('Aware Biometrics', 'Aware', 'biometrics', 0, 0, None,
     "Aware's biometric platform providing facial, fingerprint, and multimodal recognition.",
     ['Aware', 'Aware Biometrics', 'Aware Inc']),
    ('Axon Evidence', 'Axon', 'forensics', 1, 0, None,
     'Digital evidence management platform (evidence.com) with AI-driven redaction, transcription, and video retention used by law enforcement.',
     ['Axon Evidence', 'Axon Evidence.com', 'Evidence.com', 'Axon Video Retention Solution (VRS)', 'Axon VRS', 'Axon Evidence Redaction', 'Axon Evidence Digital Evidence Management']),
    ('Axon FUSUS', 'Axon', 'physical_security', 0, 0, 'Axon Evidence',
     'Real-time crime center platform that integrates camera feeds, sensors, and analytics for law-enforcement situational awareness.',
     ['Axon FUSUS', 'FUSUS']),
    ('Azure Data Factory', 'Microsoft', 'data_analytics', 0, 0, None,
     'Microsoft Azure data integration service with embedded AI features such as anomaly detection and data-quality scoring.',
     ['Azure Data Factory', 'ADF']),
    ('BD Pyxis MedStation', 'Becton Dickinson', 'clinical_decision_support', 0, 0, None,
     'Automated medication-dispensing system with predictive analytics for inventory and diversion detection.',
     ['BD Pyxis', 'BD Pyxis MedStation', 'Pyxis MedStation']),
    ('Bloomberg Government', 'Bloomberg', 'investigative_data', 0, 0, None,
     'Bloomberg Government (BGOV) provides policy, regulatory, and procurement analytics for federal stakeholders.',
     ['Bloomberg Government', 'BGOV', 'Bloomberg Government (BGOV)']),
    ('BriefCatch', 'BriefCatch', 'legal_research', 1, 0, None,
     'AI-powered legal-writing editor that suggests style, citation, and clarity improvements to briefs and memoranda.',
     ['BriefCatch', 'Lawcatch BriefCatch']),
    ('Broadcom Code for Z', 'Broadcom', 'code_modernization', 1, 0, None,
     'Mainframe code-modernization tool providing AI-assisted analysis and refactoring of COBOL and z/OS applications.',
     ['Broadcom Code for Z', 'Code for Z']),
    ('Buzzsprout CoHost AI', 'Buzzsprout', 'media_analysis', 1, 0, None,
     "Buzzsprout's CoHost AI generates podcast titles, descriptions, transcripts, and chapter markers from uploaded audio.",
     ['CoHost AI', 'Buzzsprout CoHost', 'Buzzsprout CoHost AI']),
    ('CargoNet', 'Verisk', 'investigative_data', 0, 0, None,
     'Verisk CargoNet aggregates cargo theft incident data and applies analytics to predict and disrupt supply-chain crime.',
     ['CargoNet', 'Verisk CargoNet']),
    ('Cell Hawk', 'LeadsOnline', 'investigative_data', 0, 0, None,
     'LeadsOnline Cell Hawk parses and visualizes call detail records and tower data for investigations.',
     ['Cell Hawk', 'CellHawk', 'LeadsOnline Cell Hawk']),
    ('Cisco Identity Services Engine', 'Cisco', 'security_tool', 0, 0, None,
     'Cisco ISE network access control platform that uses ML for device profiling and posture assessment.',
     ['Cisco Identity Services Engine', 'Cisco ISE', 'Cisco Identify Services engine', 'ISE']),
    ('Cisco Secure Network Analytics', 'Cisco', 'security_tool', 0, 0, None,
     "Cisco's network detection-and-response platform (formerly Stealthwatch) using ML to surface anomalous network behavior.",
     ['Cisco Secure Network Analytics', 'Stealthwatch', 'Cisco Stealthwatch']),
    ('Cloudflare Turnstile', 'Cloudflare', 'security_tool', 0, 0, None,
     "Cloudflare's privacy-preserving bot detection and CAPTCHA-replacement service.",
     ['Cloudflare Turnstile', 'Turnstile']),
    ('CoCounsel', 'Thomson Reuters', 'legal_research', 1, 0, None,
     'Thomson Reuters CoCounsel is a generative AI legal assistant for research, document review, and drafting.',
     ['CoCounsel', 'Cocounsel AI', 'Thomson Reuters CoCounsel', 'Casetext CoCounsel']),
    ('Cofense PhishMe', 'Cofense', 'security_tool', 0, 0, None,
     "Cofense's phishing simulation and reporting platform with ML-based threat triage.",
     ['Cofense', 'Cofense PhishMe', 'PhishMe']),
    ('Conductor Conduit AI', 'Conductor', 'document_ai', 1, 0, None,
     "Conductor's Conduit AI platform for document review and litigation workflows.",
     ['Conduit AI', 'Conductor Conduit AI']),
    ('Critical Mention', 'Critical Mention', 'media_analysis', 0, 0, None,
     'Real-time broadcast and online media monitoring with transcription and sentiment analysis.',
     ['Critical Mention']),
    ('DeepEMhancer', 'Open source (CSIC)', 'scientific_ml', 0, 0, None,
     'Deep-learning post-processing tool that sharpens and denoises CryoEM density maps.',
     ['DeepEMhancer']),
    ('Descript', 'Descript', 'media_analysis', 1, 0, None,
     'AI-powered audio and video editor with transcription, voice cloning, and text-based editing.',
     ['Descript']),
    ('Dun & Bradstreet', 'Dun & Bradstreet', 'investigative_data', 0, 0, None,
     'Dun & Bradstreet business establishments and risk data with AI-driven anomaly and fraud-detection analytics.',
     ['Dun & Bradstreet', 'D&B', 'Dun & Bradstreet Business Establishments Data']),
    ('ELSAG ALPR', 'Leonardo', 'computer_vision', 0, 0, None,
     'Leonardo ELSAG license-plate-reader cameras and back-end analytics used by law enforcement.',
     ['ELSAG', 'ELSAG/Leonardo', 'ELSAG ALPR', 'Leonardo ELSAG']),
    ('Elastic Stack', 'Elastic', 'search', 0, 0, None,
     'Elastic Stack (Elasticsearch, Logstash, Kibana) for search, analytics, and observability with built-in ML jobs.',
     ['Elastic Stack', 'Elastic Stack Technology (ELK)', 'ELK', 'ELK Stack', 'Elasticsearch']),
    ('Elsa (FDA)', 'FDA (internal, vendor-supported)', 'general_llm', 1, 0, None,
     "FDA's Elsa is an internal generative AI assistant used by FDA staff for document drafting and search.",
     ['Elsa', 'Elsa GenAI Chat Tool', 'FDA Elsa']),
    ('EnerGPT', 'Unknown / DOE-targeted vendor', 'general_llm', 1, 0, None,
     'DOE-targeted generative AI assistant tuned for energy-domain queries; vendor not yet confirmed in inventory text.',
     ['EnerGPT']),
    ('Fiji ImageJ', 'Open source (NIH ImageJ / Fiji community)', 'scientific_ml', 0, 0, None,
     'Fiji is the bundled ImageJ distribution for scientific image analysis; widely used with ML plugins for microscopy.',
     ['FIJI', 'Fiji', 'Fiji ImageJ', 'ImageJ']),
    ('FirstTwo', 'FirstTwo', 'investigative_data', 0, 0, None,
     'Geospatial OSINT platform that aggregates address, person, and location data for investigative lookups.',
     ['FirstTwo', 'First Two', 'FirstTwo / First Two']),
    ('Flock Safety', 'Flock Safety', 'computer_vision', 0, 0, None,
     'Cloud-based license-plate-reader and camera network with AI vehicle and behavior analytics for law enforcement.',
     ['Flock Safety', 'Flock', 'Flock LPR']),
    ('Genetec Security Center', 'Genetec', 'physical_security', 0, 0, None,
     'Unified physical-security platform with video management, access control, and AI-driven video analytics.',
     ['Genetec', 'Genetec Security Center']),
    ('Griffeye Analyze', 'Griffeye', 'forensics', 0, 0, None,
     'Forensic media analysis platform used by law enforcement to triage CSAM and other illicit imagery with classifiers.',
     ['Griffeye', 'Griffeye Analyze']),
    ('Harvey', 'Harvey', 'legal_research', 1, 0, None,
     'Domain-specific generative AI legal assistant for law firms and legal departments.',
     ['Harvey', 'harvey.ai', 'Harvey AI']),
    ('Hootsuite', 'Hootsuite', 'social_listening', 1, 0, None,
     'Social media management platform with AI-assisted content generation and analytics.',
     ['Hootsuite']),
    ('IBM watsonx Code Assistant', 'IBM', 'coding_assistant', 1, 0, None,
     'IBM watsonx Code Assistant including the Code Assistant for Z mainframe modernization variant.',
     ['IBM watsonx Code Assistant', 'IBM WatsonX Code Assistant', 'watsonx Code Assistant', 'watsonx Code Assistant for Z']),
    ('ISO ClaimSearch', 'Verisk', 'investigative_data', 0, 0, None,
     'Verisk ISO ClaimSearch is the all-claims database with analytics used by NICB and insurers to detect fraud.',
     ['ISO ClaimSearch', 'National Insurance Crime Bureau ISO ClaimSearch', 'NICB ISO ClaimSearch']),
    ('Imaris', 'Oxford Instruments', 'scientific_ml', 0, 0, None,
     'Imaris microscopy image-analysis software with ML-based segmentation and tracking.',
     ['Imaris', 'Oxford Instruments Imaris']),
    ('LaserAI', 'LaserAI', 'document_ai', 1, 0, None,
     'Commercial systematic-review automation product that uses ML to screen and extract from scientific literature.',
     ['LaserAI', 'Laser AI']),
    ('Lenel OnGuard', 'LenelS2 (Honeywell)', 'physical_security', 0, 0, None,
     'Lenel OnGuard physical access control system with analytics for credential and intrusion events.',
     ['Lenel', 'Lenel OnGuard', 'OnGuard']),
    ('Lexis+ Protege', 'LexisNexis', 'legal_research', 1, 0, 'Lexis+ AI',
     'LexisNexis Protege is a personalized generative AI legal assistant; distinct from the broader Lexis+ AI platform.',
     ['Lexis Protege', 'Lexis+ Protege', 'Protege']),
    ('Litera TOA Builder', 'Litera', 'legal_research', 0, 0, None,
     'Litera (formerly Levit & James) Word plugin for automated table-of-authorities and legal document drafting.',
     ['Litera TOA Builder', 'Levit & James Word plugin', 'Levit & James', 'TOA Builder']),
    ('Lumivero NVivo', 'Lumivero', 'data_analytics', 1, 0, None,
     'NVivo qualitative data analysis tool with AI-assisted coding and theme detection.',
     ['NVivo', 'Lumivero NVivo', 'Lumivero, NVivo']),
    ('Mark43', 'Mark43', 'investigative_data', 1, 0, None,
     'Cloud-based public-safety records management and CAD platform with AI-assisted report writing.',
     ['Mark43', 'Mark43 Public Safety Records', 'Mark43 RMS']),
    ('Milestone XProtect', 'Milestone Systems', 'physical_security', 0, 0, None,
     'Milestone XProtect video management software with integrated AI analytics for object and event detection.',
     ['Milestone', 'Milestone XProtect', 'XProtect']),
    ('ModelAngelo', 'Open source (MRC LMB)', 'scientific_ml', 0, 0, None,
     'Deep-learning tool for automated atomic-model building from CryoEM density maps.',
     ['ModelAngelo', 'Model Angelo']),
    ('NetDocuments', 'NetDocuments', 'document_ai', 1, 0, None,
     'Cloud document and email management for legal/professional services with predictive filing and GenAI features.',
     ['NetDocuments']),
    ('Nlets LPR Pointer Index', 'Nlets', 'investigative_data', 0, 0, None,
     'Nlets-operated nationwide license-plate-reader pointer index that federates LPR hits across state and local systems.',
     ['Nlets Nationwide License Plate Reader Pointer Index', 'Nlets LPR Pointer Index', 'Nlets LPR']),
    ('Nuance Dragon', 'Nuance (Microsoft)', 'transcription', 0, 0, None,
     'Nuance Dragon professional speech recognition and dictation product family.',
     ['Dragon', 'Nuance Dragon', 'Dragon NaturallySpeaking', 'Dragon Professional']),
    ('OnCue Trial Presentation', 'OnCue Technology', 'legal_research', 0, 0, None,
     'Trial presentation software used by litigators to organize and display exhibits and transcripts in court.',
     ['OnCue', 'OnCue Technology', 'OnCue Trial Presentation']),
    ('PDRI Automatically-Scored Writing Assessment', 'PDRI', 'nlp_specific', 0, 0, None,
     "PDRI's commercial automatically-scored writing assessment used in federal hiring and selection.",
     ['PDRI AWA', 'Personnel Decisions Research Institutes, LLC (PDRI)', 'PDRI Automatically-Scored Writing Assessment']),
    ('Pearson Q-interactive', 'Pearson', 'clinical_decision_support', 0, 0, None,
     "Pearson's tablet-based platform for administering and scoring psychological and cognitive assessments.",
     ['Pearson Assessments', 'Pearson Q-interactive', 'Q-interactive']),
    ('Plexis Quantum Choice', 'Plexis', 'data_analytics', 0, 0, None,
     'Plexis Quantum Choice claims adjudication and benefits-administration platform with rules and ML.',
     ['Quantum Choice from Plexis', 'Plexis Quantum Choice', 'Quantum Choice']),
    ('ProLaw', 'Thomson Reuters', 'legal_research', 0, 0, None,
     'Thomson Reuters ProLaw legal practice management with integrated search and AI features.',
     ['ProLaw', 'Thomson Reuters ProLaw']),
    ('Ptolemy', 'Open source', 'scientific_ml', 0, 0, None,
     'Open-source CryoEM micrograph screening and triage tool using ML.',
     ['Ptolemy']),
    ('Qualtrics', 'Qualtrics', 'data_analytics', 1, 0, None,
     'Experience-management and survey platform with AI-driven sentiment, topic, and text analytics.',
     ['Qualtrics', 'Qualtrics XM']),
    ('RWS Trados', 'RWS', 'translation', 1, 0, None,
     'Trados is a leading computer-assisted translation suite with neural MT and translation-memory features.',
     ['RWS Trados', 'Trados', 'SDL Trados']),
    ('Rangeland Analysis Platform', 'University of Montana / NRCS', 'scientific_ml', 0, 0, None,
     'Public Rangeland Analysis Platform on Google Cloud providing remote-sensing-derived rangeland vegetation models.',
     ['Rangeland Analysis Platform', 'RAP']),
    ('Rank One Computing', 'Rank One Computing', 'biometrics', 0, 0, None,
     'Rank One Computing face recognition and biometric SDK used in identity and law-enforcement deployments.',
     ['Rank One Computing', 'Rank One', 'ROC']),
    ('Raytheon BBN M3S', 'Raytheon BBN', 'media_analysis', 0, 0, None,
     "Raytheon BBN's Multimedia Monitoring System (M3S) ingests and analyzes broadcast and online media for situational awareness.",
     ['Raytheon Multimedia Monitoring System (M3S)', 'M3S', 'Raytheon BBN M3S']),
    ('SAS Analytics', 'SAS', 'data_analytics', 0, 0, None,
     'SAS statistical analytics and ML platform used across federal agencies for classification and risk modeling.',
     ['SAS', 'SAS Analytics', 'SAS Viya', 'SAS Enterprise Miner']),
    ('ShotSpotter', 'SoundThinking', 'audio_analysis', 0, 0, None,
     'SoundThinking ShotSpotter acoustic gunshot detection and localization service for law enforcement.',
     ['ShotSpotter', 'SoundThinking ShotSpotter']),
    ('Smiths Detection TruNarc', 'Smiths Detection', 'forensics', 0, 0, None,
     'Handheld Raman-spectroscopy narcotics analyzer with onboard classification of controlled substances.',
     ['TruNarc', 'Smiths Detection TruNarc', 'TruNarc, Smiths Detection']),
    ('Spokeo', 'Spokeo', 'investigative_data', 0, 0, None,
     'Spokeo people-search service aggregating public records for investigative lookups.',
     ['Spokeo']),
    ('TLOxp', 'TransUnion', 'investigative_data', 0, 0, None,
     'TransUnion TLOxp investigative search platform that links person, asset, and association records for due diligence.',
     ['TLOxp', 'TLO', 'TransUnion TLOxp']),
    ('Techsmith Audiate', 'TechSmith', 'media_analysis', 1, 0, None,
     'TechSmith Audiate is a text-based audio editor with AI transcription and voice cleanup.',
     ['Audiate', 'Techsmith Audiate', 'TechSmith Audiate']),
    ('TekSynap SimplifAI', 'TekSynap', 'general_llm', 1, 0, None,
     "TekSynap's SimplifAI commercial generative AI platform sold to federal customers.",
     ['TekSynap SimplifAI', 'SimplifAI']),
    ('Topaz CryoEM', 'Open source', 'scientific_ml', 0, 0, None,
     'Topaz is a deep-learning-based particle-picking tool for CryoEM data.',
     ['Topaz', 'Topaz CryoEM', 'Topaz Picker']),
    ('Trunet Biometrics', 'Advanced Technologies Group', 'biometrics', 0, 0, None,
     'Advanced Technologies Group Trunet biometric capture and matching system.',
     ['Trunet', 'Trunet Systems', 'Trunet Biometrics']),
    ('Unison PRISM', 'Unison', 'supply_chain', 0, 0, None,
     'Unison PRISM federal procurement and acquisition platform with embedded analytics.',
     ['Unison', 'Unison PRISM', 'PRISM']),
    ('Verkada', 'Verkada', 'physical_security', 0, 0, None,
     'Cloud-managed video surveillance, access control, and sensor platform with on-camera AI analytics.',
     ['Verkada']),
    ('reCAPTCHA', 'Google', 'security_tool', 0, 0, None,
     'Google reCAPTCHA bot detection service that uses behavioral signals and risk scoring.',
     ['reCAPTCHA', 'Google reCAPTCHA']),
]
