"""Integrate the 5 unmapped-research agent outputs into the seed tree.

Strategy:
  1. Read all 5 audit/unmapped_research/agent*/proposed_additions.json files.
  2. Sort add_to_seed entries by parent_path depth ASC, so intermediate
     parents (e.g., NSF/BIO directorate) land before child offices.
  3. For each add_to_seed entry, locate its parent in the in-memory ORG_TREE
     and append the new child node.
  4. For each alias_existing entry, find the existing target node by
     parent_path + abbreviation and append the new alias.
  5. Always include the unmapped bureau_component string itself as an alias
     of the new node — that's what the backfill matches against.
  6. Write the updated tree back to data/federal_hierarchy_seed.py with a
     deterministic, human-readable serializer.
  7. Emit audit/unmapped_research/_INTEGRATION_REPORT.md summarizing what
     applied, what was skipped, and what needs human review.

After this script runs, re-run seed → backfill → org-maturity to land the
new mappings in the DB.
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESEARCH_DIR = ROOT / "audit" / "unmapped_research"
SEED_PATH = ROOT / "data" / "federal_hierarchy_seed.py"
REPORT_PATH = RESEARCH_DIR / "_INTEGRATION_REPORT.md"

sys.path.insert(0, str(ROOT))
from data.federal_hierarchy_seed import ORG_TREE  # noqa: E402


# ---------------------------------------------------------------------------
# Tree manipulation
# ---------------------------------------------------------------------------

def find_node(tree: list[dict], path: list[str]) -> dict | None:
    """Walk the tree by abbreviation path and return the deepest matching node."""
    if not path:
        return None
    cursor = None
    siblings: list[dict] = tree
    for abbr in path:
        cursor = next((n for n in siblings if (n.get("abbreviation") or "") == abbr), None)
        if cursor is None:
            return None
        siblings = cursor.get("children") or []
    return cursor


def attach_child(parent: dict, child: dict) -> None:
    parent.setdefault("children", []).append(child)


def add_alias(node: dict, alias: str) -> None:
    aliases = node.setdefault("aliases", [])
    if alias and alias not in aliases:
        aliases.append(alias)


# ---------------------------------------------------------------------------
# Serialization (writes a clean Python file with the new ORG_TREE)
# ---------------------------------------------------------------------------

PREAMBLE = '''"""Federal organizations hierarchy — seed data.

The tree covers every CFO Act department, every independent agency that filed a
2025 inventory, and the sub-agencies / labs / centers / components that appear
in our use_cases.bureau_component data with at least 2 references.

Each node has:
    name (str, required)
    abbreviation (str, optional but strongly preferred)
    level ('department' | 'independent' | 'sub_agency' | 'office' | 'component')
    is_cfo_act_agency (bool, defaults False)
    is_cabinet_department (bool, defaults False)
    aliases (list[str], optional) - extra strings the backfill should recognize
                                    as referring to this org (e.g. full bureau
                                    names, casing variants, parenthetical codes)
    children (list[Node], optional)

The seed script computes slug + hierarchy_path automatically.

This file is regenerated by scripts/apply_unmapped_research.py whenever new
unmapped-bureau research lands. Hand-edits should go either via that script's
inputs (audit/unmapped_research/agent*/proposed_additions.json) or directly
here — but if you hand-edit, expect a future apply pass to overwrite.
"""
from __future__ import annotations

ORG_TREE: list[dict] = '''


# Field order for stable, readable output
NODE_FIELD_ORDER = [
    "name", "short_name", "abbreviation", "level",
    "is_cfo_act_agency", "is_cabinet_department",
    "website", "description", "aliases", "children",
]


def render_value(v, indent: int) -> str:
    pad = "    " * indent
    if isinstance(v, dict):
        return render_node(v, indent)
    if isinstance(v, list):
        if not v:
            return "[]"
        if v and isinstance(v[0], dict):
            inner = ",\n".join(pad + "    " + render_value(item, indent + 1) for item in v)
            return f"[\n{inner},\n{pad}]"
        # list of strings/scalars
        items = ", ".join(repr(item) for item in v)
        return f"[{items}]"
    return repr(v)


def render_node(node: dict, indent: int) -> str:
    pad = "    " * indent
    inner_pad = "    " * (indent + 1)
    parts = []
    for key in NODE_FIELD_ORDER:
        if key not in node:
            continue
        v = node[key]
        if v is None or v is False:
            # Skip default-falsy fields to keep output clean
            if key in ("is_cfo_act_agency", "is_cabinet_department"):
                continue
        parts.append(f"{inner_pad}{key!r}: {render_value(v, indent + 1)}")
    body = ",\n".join(parts)
    return "{\n" + body + ",\n" + pad + "}"


def write_seed_file(tree: list[dict]) -> None:
    body = "[\n"
    for top in tree:
        body += "    " + render_node(top, 1) + ",\n"
    body += "]\n"
    SEED_PATH.write_text(PREAMBLE + body)


# ---------------------------------------------------------------------------
# Main integration
# ---------------------------------------------------------------------------

def main() -> int:
    # Load all agent outputs in a deterministic order (agent1, agent2, ...)
    all_entries: list[dict] = []
    by_agent: dict[str, list[dict]] = {}
    for agent_dir in sorted(RESEARCH_DIR.glob("agent*")):
        path = agent_dir / "proposed_additions.json"
        if not path.exists():
            continue
        with open(path) as f:
            entries = json.load(f)
        by_agent[agent_dir.name] = entries
        all_entries.extend(entries)

    print(f"[integrate] loaded {len(all_entries)} total proposed entries from {len(by_agent)} agents")

    add_entries = [e for e in all_entries if e["decision"] == "add_to_seed"]
    alias_entries = [e for e in all_entries if e["decision"] == "alias_existing"]
    split_entries = [e for e in all_entries if e["decision"] == "split_multi_bureau"]
    skip_entries = [e for e in all_entries if e["decision"] == "generic_skip"]
    unclear_entries = [e for e in all_entries if e["decision"] == "unclear"]

    # Sort add_to_seed by parent_path depth ASC so intermediates land first.
    add_entries.sort(key=lambda e: len(e.get("parent_path") or []))

    stats = {
        "added": 0,
        "added_aliases": 0,
        "alias_only": 0,
        "skip_no_parent": [],
        "duplicate_abbr_in_parent": [],
    }

    for entry in add_entries:
        parent_path = entry.get("parent_path") or []
        parent = find_node(ORG_TREE, parent_path)
        if parent is None:
            stats["skip_no_parent"].append((entry["agency"], entry["bureau_component"], parent_path, entry.get("name")))
            continue

        # Build the new node
        node = {"name": entry["name"]}
        if entry.get("abbreviation"):
            node["abbreviation"] = entry["abbreviation"]
        if entry.get("level"):
            node["level"] = entry["level"]
        if entry.get("description"):
            node["description"] = entry["description"]

        aliases = list(entry.get("aliases") or [])
        # Always include the original bureau_component string as an alias so
        # the default backfill branch picks it up.
        bc = (entry.get("bureau_component") or "").strip()
        if bc and bc not in aliases:
            aliases.append(bc)
        if aliases:
            node["aliases"] = aliases

        # Skip if a sibling with the same abbreviation already exists (likely
        # a duplicate add — common when agents independently propose the same
        # well-known sub-agency).
        siblings = parent.get("children") or []
        existing = next(
            (s for s in siblings if s.get("abbreviation") and s.get("abbreviation") == entry.get("abbreviation")),
            None,
        )
        if existing is not None:
            # Promote any new aliases onto the existing node instead.
            for a in aliases:
                add_alias(existing, a)
            stats["duplicate_abbr_in_parent"].append((entry["agency"], entry.get("abbreviation"), parent_path))
            stats["added_aliases"] += len(aliases)
            continue

        attach_child(parent, node)
        stats["added"] += 1

    # alias_existing — find target by parent_path + abbreviation, add aliases
    for entry in alias_entries:
        parent_path = entry.get("parent_path") or []
        target = find_node(ORG_TREE, parent_path + [entry.get("abbreviation")] if entry.get("abbreviation") else parent_path)
        if target is None and parent_path:
            # Fall back: just look at the parent and find by name match
            parent = find_node(ORG_TREE, parent_path[:-1] if len(parent_path) > 1 else parent_path)
            if parent is not None:
                target = next(
                    (n for n in (parent.get("children") or []) if n.get("name") == entry.get("name")),
                    None,
                )
        if target is None:
            stats["skip_no_parent"].append((entry["agency"], entry["bureau_component"], parent_path, "alias target not found"))
            continue
        added = 0
        for a in entry.get("aliases") or []:
            add_alias(target, a)
            added += 1
        bc = (entry.get("bureau_component") or "").strip()
        if bc:
            add_alias(target, bc)
            added += 1
        stats["alias_only"] += 1
        stats["added_aliases"] += added

    # Write the updated seed file
    write_seed_file(ORG_TREE)
    print(f"[integrate] wrote updated seed: {SEED_PATH.relative_to(ROOT)}")

    # Build the integration report
    lines = []
    lines.append("# Unmapped-research integration report")
    lines.append("")
    lines.append(f"- Sources: {', '.join(sorted(by_agent))}")
    lines.append(f"- Total proposed entries: {len(all_entries)}")
    lines.append("")
    lines.append("## Decision counts")
    lines.append("")
    lines.append(f"- `add_to_seed`: {len(add_entries)} processed → **{stats['added']} new nodes added**, "
                 f"{stats['added_aliases']} aliases applied to existing nodes")
    lines.append(f"- `alias_existing`: {len(alias_entries)} processed → {stats['alias_only']} successful")
    lines.append(f"- `split_multi_bureau`: {len(split_entries)} (handled by backfill multi-split, not by seed)")
    lines.append(f"- `generic_skip`: {len(skip_entries)} ignored by design")
    lines.append(f"- `unclear`: {len(unclear_entries)} flagged for human review")
    lines.append("")

    if stats["duplicate_abbr_in_parent"]:
        lines.append("## Duplicate-abbreviation merges")
        lines.append("")
        lines.append("These entries had a sibling with the same abbreviation already in the parent. "
                     "Aliases from the new entry were promoted onto the existing node.")
        lines.append("")
        for agency, abbr, ppath in stats["duplicate_abbr_in_parent"]:
            lines.append(f"- {agency} > {' > '.join(ppath)} > {abbr}")
        lines.append("")

    if stats["skip_no_parent"]:
        lines.append("## Skipped (parent path not found)")
        lines.append("")
        for agency, bc, ppath, name in stats["skip_no_parent"]:
            lines.append(f"- {agency} | bureau_component=`{bc}` | parent_path=`{' > '.join(ppath)}` | {name}")
        lines.append("")

    if unclear_entries:
        lines.append("## Unclear (needs human review)")
        lines.append("")
        for e in unclear_entries:
            lines.append(f"- {e['agency']} > `{e['bureau_component']}` (occurrence_count={e['occurrence_count']}): "
                         f"{e.get('notes') or ''}")
        lines.append("")

    if split_entries:
        lines.append("## Multi-bureau splits (backfill handles)")
        lines.append("")
        for e in split_entries:
            lines.append(f"- {e['agency']} > `{e['bureau_component']}` → {e.get('notes') or 'split into constituent bureaus'}")
        lines.append("")

    REPORT_PATH.write_text("\n".join(lines))
    print(f"[integrate] wrote report: {REPORT_PATH.relative_to(ROOT)}")
    print()
    print(f"[integrate] {stats['added']} new nodes added")
    print(f"[integrate] {stats['added_aliases']} aliases applied")
    if stats["skip_no_parent"]:
        print(f"[integrate] WARNING: {len(stats['skip_no_parent'])} entries skipped (parent path not found)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
