"""Federal organizations hierarchy — seed data.

The tree covers every CFO Act department, every independent agency that filed a
2025 inventory, and the sub-agencies / labs / centers / components that appear
in our use_cases.bureau_component data with at least 2 references.

Each node has:
    name (str, required)
    abbreviation (str, optional but strongly preferred)
    level ('department' | 'independent' | 'sub_agency' | 'office' | 'component')
    is_cfo_act_agency (bool, defaults False)
    is_cabinet_department (bool, defaults False)
    aliases (list[str], optional) - extra strings the backfill should recognize
                                    as referring to this org (e.g. full bureau
                                    names, casing variants, parenthetical codes)
    children (list[Node], optional)

The seed script computes slug + hierarchy_path automatically.

This file is regenerated by scripts/apply_unmapped_research.py whenever new
unmapped-bureau research lands. Hand-edits should go either via that script's
inputs (audit/unmapped_research/agent*/proposed_additions.json) or directly
here — but if you hand-edit, expect a future apply pass to overwrite.
"""
from __future__ import annotations

ORG_TREE: list[dict] = [
    {
        'name': 'Department of Agriculture',
        'abbreviation': 'USDA',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
        'children': [
            {
                'name': 'Agricultural Research Service',
                'abbreviation': 'ARS',
                'level': 'sub_agency',
            },
            {
                'name': 'Natural Resources Conservation Service',
                'abbreviation': 'NRCS',
                'level': 'sub_agency',
            },
            {
                'name': 'Forest Service',
                'abbreviation': 'FS',
                'level': 'sub_agency',
            },
            {
                'name': 'Farm Service Agency',
                'abbreviation': 'FSA',
                'level': 'sub_agency',
            },
            {
                'name': 'Animal and Plant Health Inspection Service',
                'abbreviation': 'APHIS',
                'level': 'sub_agency',
            },
            {
                'name': 'Food Safety and Inspection Service',
                'abbreviation': 'FSIS',
                'level': 'sub_agency',
            },
            {
                'name': 'Food and Nutrition Service',
                'abbreviation': 'FNS',
                'level': 'sub_agency',
            },
            {
                'name': 'Risk Management Agency',
                'abbreviation': 'RMA',
                'level': 'sub_agency',
            },
            {
                'name': 'Economic Research Service',
                'abbreviation': 'ERS',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of the Chief Information Officer',
                'abbreviation': 'OCIO',
                'level': 'office',
                'aliases': ['Office of the CIO'],
            },
            {
                'name': 'Natural Resources and Environment',
                'abbreviation': 'NRE',
                'level': 'sub_agency',
            },
            {
                'name': 'Research, Education, and Economics',
                'abbreviation': 'REE',
                'level': 'sub_agency',
                'aliases': ['Research, Education and Economics'],
            },
            {
                'name': 'Farm Production and Conservation',
                'abbreviation': 'FPAC',
                'level': 'sub_agency',
            },
            {
                'name': 'Marketing and Regulatory Programs',
                'abbreviation': 'MRP',
                'level': 'sub_agency',
            },
            {
                'name': 'Food Safety',
                'abbreviation': 'FoodSafety',
                'level': 'sub_agency',
            },
            {
                'name': 'Rural Development',
                'abbreviation': 'RD',
                'level': 'sub_agency',
            },
            {
                'name': 'Food, Nutrition, and Consumer Services',
                'abbreviation': 'FNCS',
                'level': 'sub_agency',
                'aliases': ['Food, Nutrition, and Consumer Services'],
            },
            {
                'name': 'Office of Safety, Security and Protection',
                'abbreviation': 'OSSP',
                'level': 'office',
                'aliases': ['Office of Safety, Security, and Protection'],
            },
            {
                'name': 'Departmental Administration',
                'abbreviation': 'DA',
                'level': 'sub_agency',
                'aliases': ['Departmental Administration'],
            },
            {
                'name': 'Office of Homeland Security',
                'abbreviation': 'OHS',
                'level': 'office',
                'aliases': ['Office Of Homeland Security', 'OHSEC', 'Office of Homeland Security and Emergency Coordination'],
            },
        ],
    },
    {
        'name': 'Department of Commerce',
        'abbreviation': 'DOC',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
        'children': [
            {
                'name': 'National Oceanic and Atmospheric Administration',
                'abbreviation': 'NOAA',
                'level': 'sub_agency',
            },
            {
                'name': 'U.S. Census Bureau',
                'abbreviation': 'Census',
                'level': 'sub_agency',
                'aliases': ['Census Bureau', 'U.S. Census'],
            },
            {
                'name': 'U.S. Patent and Trademark Office',
                'abbreviation': 'USPTO',
                'level': 'sub_agency',
            },
            {
                'name': 'International Trade Administration',
                'abbreviation': 'ITA',
                'level': 'sub_agency',
            },
            {
                'name': 'National Telecommunications and Information Administration',
                'abbreviation': 'NTIA',
                'level': 'sub_agency',
            },
            {
                'name': 'National Institute of Standards and Technology',
                'abbreviation': 'NIST',
                'level': 'sub_agency',
            },
            {
                'name': 'First Responder Network Authority',
                'abbreviation': 'FirstNet',
                'level': 'sub_agency',
            },
            {
                'name': 'Bureau of Economic Analysis',
                'abbreviation': 'BEA',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of the Secretary',
                'abbreviation': 'OS',
                'level': 'office',
            },
        ],
    },
    {
        'name': 'Department of Defense',
        'abbreviation': 'DoD',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
    },
    {
        'name': 'Department of Education',
        'abbreviation': 'ED',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
        'children': [
            {
                'name': 'Federal Student Aid',
                'abbreviation': 'FSA',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of the Chief Information Officer',
                'abbreviation': 'OCIO',
                'level': 'office',
            },
            {
                'name': 'Office of Postsecondary Education',
                'abbreviation': 'OPE',
                'level': 'office',
            },
            {
                'name': 'Office of Special Education and Rehabilitative Services',
                'abbreviation': 'OSERS',
                'level': 'office',
                'aliases': ['Office of Special Education and Rehabilitee Services'],
            },
            {
                'name': 'Office of Finance and Operations',
                'abbreviation': 'OFO',
                'level': 'office',
                'children': [
                    {
                        'name': 'Grants Management Policy Division',
                        'abbreviation': 'GMPD',
                        'level': 'office',
                        'aliases': ['Grants Management Policy Division', 'GMPD'],
                    },
                    {
                        'name': 'Contracts and Acquisitions Management',
                        'abbreviation': 'CAM',
                        'level': 'office',
                        'aliases': ['Contracts & Acquisitions Management', 'CAM'],
                    },
                ],
            },
            {
                'name': 'Office of the Chief Data Officer',
                'abbreviation': 'OCDO',
                'level': 'office',
            },
            {
                'name': 'Office of the General Counsel',
                'abbreviation': 'OGC',
                'level': 'office',
            },
            {
                'name': 'Office of Elementary and Secondary Education',
                'abbreviation': 'OESE',
                'level': 'office',
                'children': [
                    {
                        'name': 'Office of Migrant Education',
                        'abbreviation': 'OME',
                        'level': 'office',
                        'aliases': ['Office of Migrant Education', 'OME'],
                    },
                ],
            },
            {
                'name': 'Institute of Education Sciences',
                'abbreviation': 'IES',
                'level': 'sub_agency',
            },
            {
                'name': 'Office for Civil Rights',
                'abbreviation': 'OCR',
                'level': 'office',
            },
            {
                'name': 'Office of Career, Technical, and Adult Education',
                'abbreviation': 'OCTAE',
                'level': 'office',
            },
            {
                'name': 'Office of the Under Secretary',
                'abbreviation': 'OUS',
                'level': 'office',
                'aliases': ['Office of the Under Secretary', 'OUS'],
            },
            {
                'name': 'Office of the Deputy Secretary',
                'abbreviation': 'ODS',
                'level': 'office',
                'aliases': ['Office of the Deputy Secretary', 'ODS'],
            },
            {
                'name': 'Office of Communications and Outreach',
                'abbreviation': 'OCO',
                'level': 'office',
                'aliases': ['Office of Communications and Outreach', 'OCO'],
            },
            {
                'name': 'Office of Educational Technology',
                'abbreviation': 'OET',
                'level': 'office',
                'aliases': ['Office of Educational Technology', 'OET'],
            },
        ],
    },
    {
        'name': 'Department of Energy',
        'abbreviation': 'DOE',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
        'children': [
            {
                'name': 'Pacific Northwest National Laboratory',
                'abbreviation': 'PNNL',
                'level': 'sub_agency',
            },
            {
                'name': 'Idaho National Laboratory',
                'abbreviation': 'INL',
                'level': 'sub_agency',
                'aliases': ['NE INL'],
            },
            {
                'name': 'Brookhaven National Laboratory',
                'abbreviation': 'BNL',
                'level': 'sub_agency',
            },
            {
                'name': 'Oak Ridge National Laboratory',
                'abbreviation': 'ORNL',
                'level': 'sub_agency',
            },
            {
                'name': 'Fermi National Accelerator Laboratory',
                'abbreviation': 'FNAL',
                'level': 'sub_agency',
            },
            {
                'name': 'National Energy Technology Laboratory',
                'abbreviation': 'NETL',
                'level': 'sub_agency',
            },
            {
                'name': 'Los Alamos National Laboratory',
                'abbreviation': 'LANL',
                'level': 'sub_agency',
                'aliases': ['EMLA', 'EM Los Alamos Field Site'],
            },
            {
                'name': 'Lawrence Livermore National Laboratory',
                'abbreviation': 'LLNL',
                'level': 'sub_agency',
            },
            {
                'name': 'SLAC National Accelerator Laboratory',
                'abbreviation': 'SLAC',
                'level': 'sub_agency',
            },
            {
                'name': 'National Renewable Energy Laboratory',
                'abbreviation': 'NREL',
                'level': 'sub_agency',
            },
            {
                'name': 'Argonne National Laboratory',
                'abbreviation': 'ANL',
                'level': 'sub_agency',
            },
            {
                'name': 'Sandia National Laboratories',
                'abbreviation': 'SNL',
                'level': 'sub_agency',
            },
            {
                'name': 'Princeton Plasma Physics Laboratory',
                'abbreviation': 'PPPL',
                'level': 'sub_agency',
            },
            {
                'name': 'Y-12 National Security Complex',
                'abbreviation': 'Y-12',
                'level': 'sub_agency',
                'aliases': ['Consolidated Nuclear Security Y-12', 'YFO'],
            },
            {
                'name': 'Pantex Plant',
                'abbreviation': 'Pantex',
                'level': 'sub_agency',
                'aliases': ['PanTeXas Deterrence Pantex', 'PFO'],
            },
            {
                'name': 'Ames Laboratory',
                'abbreviation': 'Ames',
                'level': 'sub_agency',
            },
            {
                'name': 'Strategic Petroleum Reserve',
                'abbreviation': 'SPR',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of Science',
                'abbreviation': 'SC',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of Cybersecurity, Energy Security, and Emergency Response',
                'abbreviation': 'CESER',
                'level': 'sub_agency',
            },
            {
                'name': 'Kansas City National Security Campus',
                'abbreviation': 'KCNSC',
                'level': 'sub_agency',
            },
            {
                'name': 'Savannah River Site',
                'abbreviation': 'SRS',
                'level': 'sub_agency',
                'aliases': ['SRS - ESB', 'SRS - SRNL'],
            },
            {
                'name': 'Hanford Site',
                'abbreviation': 'Hanford',
                'level': 'sub_agency',
                'aliases': ['RL - Hanford'],
            },
            {
                'name': 'Naval Reactors',
                'abbreviation': 'NR',
                'level': 'sub_agency',
                'aliases': ['NR HQ'],
            },
            {
                'name': 'Office of Energy Efficiency and Renewable Energy',
                'abbreviation': 'EE',
                'level': 'sub_agency',
                'aliases': ['EE HQ'],
            },
            {
                'name': 'Office of Environmental Management',
                'abbreviation': 'EM',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of Legacy Management',
                'abbreviation': 'LM',
                'level': 'sub_agency',
                'aliases': ['LM HQ'],
            },
            {
                'name': 'National Nuclear Security Administration',
                'abbreviation': 'NNSA',
                'level': 'sub_agency',
                'aliases': ['NA-IM', 'NNSA HQ'],
            },
            {
                'name': 'Office of Fossil Energy and Carbon Management',
                'abbreviation': 'FECM',
                'level': 'sub_agency',
            },
            {
                'name': 'Western Area Power Administration',
                'abbreviation': 'WAPA',
                'level': 'sub_agency',
            },
            {
                'name': 'Bonneville Power Administration',
                'abbreviation': 'BPA',
                'level': 'sub_agency',
            },
            {
                'name': 'Architecture, Engineering, Technology and Innovation',
                'abbreviation': 'IM-50',
                'level': 'office',
            },
            {
                'name': 'Office of Environment, Health, Safety and Security',
                'abbreviation': 'EHSS',
                'level': 'sub_agency',
                'aliases': ['EHSS HQ', 'EHSS HQ - Office of Environment Health Safety and Security (EHSS)'],
            },
            {
                'name': 'Office of Project Management',
                'abbreviation': 'PM',
                'level': 'sub_agency',
                'aliases': ['PM HQ', 'PM HQ -  Office of Project Management (PM)'],
            },
            {
                'name': 'Southwestern Power Administration',
                'abbreviation': 'SWPA',
                'level': 'sub_agency',
                'aliases': ['SWPA', 'SWPA - Southwestern Power Administration (PMA)'],
            },
            {
                'name': 'Office of the Chief Human Capital Officer',
                'abbreviation': 'HC',
                'level': 'sub_agency',
                'aliases': ['HC HQ', 'HC HQ -  Office of the Chief Human Capital Officer (HC)'],
            },
            {
                'name': 'Southeastern Power Administration',
                'abbreviation': 'SEPA',
                'level': 'sub_agency',
                'aliases': ['SEPA', 'SEPA - Southeastern Power Administration (PMA)'],
            },
            {
                'name': 'Grid Deployment Office',
                'abbreviation': 'GDO',
                'level': 'sub_agency',
                'aliases': ['GDO HQ', 'GDO HQ - Grid Deployment Office (GDO)'],
            },
            {
                'name': 'Office of Public Affairs',
                'abbreviation': 'PA',
                'level': 'office',
                'aliases': ['PA HQ', 'PA HQ -  Office of Public Affairs (PA)'],
            },
        ],
    },
    {
        'name': 'Department of Health and Human Services',
        'abbreviation': 'HHS',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
        'children': [
            {
                'name': 'Centers for Disease Control and Prevention',
                'abbreviation': 'CDC',
                'level': 'sub_agency',
            },
            {
                'name': 'Centers for Medicare and Medicaid Services',
                'abbreviation': 'CMS',
                'level': 'sub_agency',
                'children': [
                    {
                        'name': 'Center for Consumer Information and Insurance Oversight',
                        'abbreviation': 'CCIIO',
                        'level': 'office',
                    },
                    {
                        'name': 'Office of Information Technology',
                        'abbreviation': 'OIT',
                        'level': 'office',
                    },
                    {
                        'name': 'Office of Communications',
                        'abbreviation': 'OC',
                        'level': 'office',
                    },
                    {
                        'name': 'Center for Clinical Standards and Quality',
                        'abbreviation': 'CCSQ',
                        'level': 'office',
                    },
                    {
                        'name': 'Office of Financial Management',
                        'abbreviation': 'OFM',
                        'level': 'office',
                    },
                ],
            },
            {
                'name': 'Food and Drug Administration',
                'abbreviation': 'FDA',
                'level': 'sub_agency',
                'children': [
                    {
                        'name': 'Center for Drug Evaluation and Research',
                        'abbreviation': 'CDER',
                        'level': 'office',
                    },
                    {
                        'name': 'Human Foods Program',
                        'abbreviation': 'HFP',
                        'level': 'office',
                    },
                    {
                        'name': 'Office of Inspections and Investigations',
                        'abbreviation': 'OII',
                        'level': 'office',
                    },
                    {
                        'name': 'Office of the Commissioner Strategic Programs',
                        'abbreviation': 'OCS',
                        'level': 'office',
                    },
                    {
                        'name': 'Center for Biologics Evaluation and Research',
                        'abbreviation': 'CBER',
                        'level': 'office',
                    },
                    {
                        'name': 'Office of Digital Transformation',
                        'abbreviation': 'ODT',
                        'level': 'office',
                    },
                    {
                        'name': 'Center for Devices and Radiological Health',
                        'abbreviation': 'CDRH',
                        'level': 'office',
                    },
                    {
                        'name': 'Center for Tobacco Products',
                        'abbreviation': 'CTP',
                        'level': 'office',
                    },
                    {
                        'name': 'Center for Veterinary Medicine',
                        'abbreviation': 'CVM',
                        'level': 'office',
                    },
                    {
                        'name': 'Office of Regulatory Affairs',
                        'abbreviation': 'ORA',
                        'level': 'office',
                    },
                    {
                        'name': 'Office of Information Management and Technology',
                        'abbreviation': 'OIMT',
                        'level': 'office',
                    },
                ],
            },
            {
                'name': 'National Institutes of Health',
                'abbreviation': 'NIH',
                'level': 'sub_agency',
            },
            {
                'name': 'Administration for Children and Families',
                'abbreviation': 'ACF',
                'level': 'sub_agency',
            },
            {
                'name': 'Health Resources and Services Administration',
                'abbreviation': 'HRSA',
                'level': 'sub_agency',
            },
            {
                'name': 'Substance Abuse and Mental Health Services Administration',
                'abbreviation': 'SAMHSA',
                'level': 'sub_agency',
            },
            {
                'name': 'Agency for Healthcare Research and Quality',
                'abbreviation': 'AHRQ',
                'level': 'sub_agency',
                'children': [
                    {
                        'name': 'Center for Quality Improvement and Patient Safety',
                        'abbreviation': 'CQuIPS',
                        'level': 'office',
                    },
                ],
            },
            {
                'name': 'Indian Health Service',
                'abbreviation': 'IHS',
                'level': 'sub_agency',
            },
            {
                'name': 'Administration for Strategic Preparedness and Response',
                'abbreviation': 'ASPR',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of the Assistant Secretary for Financial Resources',
                'abbreviation': 'ASFR',
                'level': 'office',
                'aliases': ['ASFR/OG'],
            },
            {
                'name': 'Departmental Appeals Board',
                'abbreviation': 'DAB',
                'level': 'office',
            },
            {
                'name': 'Office of the Secretary',
                'abbreviation': 'OS',
                'level': 'office',
            },
            {
                'name': 'Office of the Assistant Secretary for Health',
                'abbreviation': 'OASH',
                'level': 'sub_agency',
            },
            {
                'name': 'Administration for Community Living',
                'abbreviation': 'ACL',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of the General Counsel',
                'abbreviation': 'OGC',
                'level': 'office',
            },
            {
                'name': 'Office of the Inspector General',
                'abbreviation': 'OIG',
                'level': 'office',
            },
            {
                'name': 'Office of Refugee Resettlement',
                'abbreviation': 'ORR',
                'level': 'office',
            },
            {
                'name': 'Assistant Secretary for Technology Policy / Office of the National Coordinator for Health IT',
                'abbreviation': 'ASTP',
                'level': 'sub_agency',
                'aliases': ['HHS/ASTP', 'ASTP', 'ONC', 'ASTP/ONC'],
            },
            {
                'name': 'Office of the Chief Information Officer',
                'abbreviation': 'OCIO',
                'level': 'office',
                'aliases': ['HHS/OCIO'],
            },
            {
                'name': 'Office for Civil Rights',
                'abbreviation': 'OCR',
                'level': 'office',
                'aliases': ['HHS/OCR'],
            },
        ],
    },
    {
        'name': 'Department of Homeland Security',
        'abbreviation': 'DHS',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
        'children': [
            {
                'name': 'U.S. Customs and Border Protection',
                'abbreviation': 'CBP',
                'level': 'sub_agency',
            },
            {
                'name': 'U.S. Immigration and Customs Enforcement',
                'abbreviation': 'ICE',
                'level': 'sub_agency',
            },
            {
                'name': 'Transportation Security Administration',
                'abbreviation': 'TSA',
                'level': 'sub_agency',
            },
            {
                'name': 'U.S. Citizenship and Immigration Services',
                'abbreviation': 'USCIS',
                'level': 'sub_agency',
            },
            {
                'name': 'Federal Emergency Management Agency',
                'abbreviation': 'FEMA',
                'level': 'sub_agency',
            },
            {
                'name': 'Cybersecurity and Infrastructure Security Agency',
                'abbreviation': 'CISA',
                'level': 'sub_agency',
            },
            {
                'name': 'U.S. Coast Guard',
                'abbreviation': 'USCG',
                'level': 'sub_agency',
            },
            {
                'name': 'U.S. Secret Service',
                'abbreviation': 'USSS',
                'level': 'sub_agency',
            },
            {
                'name': 'Countering Weapons of Mass Destruction Office',
                'abbreviation': 'CWMD',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of Homeland Security Statistics',
                'abbreviation': 'OHS',
                'level': 'office',
            },
            {
                'name': 'Management Directorate',
                'abbreviation': 'MGMT',
                'level': 'office',
            },
            {
                'name': 'Federal Law Enforcement Training Centers',
                'abbreviation': 'FLETC',
                'level': 'sub_agency',
            },
            {
                'name': 'Science and Technology Directorate',
                'abbreviation': 'S&T',
                'level': 'sub_agency',
            },
        ],
    },
    {
        'name': 'Department of Housing and Urban Development',
        'abbreviation': 'HUD',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
        'children': [
            {
                'name': 'Office of the Chief Information Officer',
                'abbreviation': 'OCIO',
                'level': 'office',
            },
            {
                'name': 'Office of Inspector General',
                'abbreviation': 'OIG',
                'level': 'office',
            },
            {
                'name': 'Government National Mortgage Association',
                'abbreviation': 'GNMA',
                'level': 'sub_agency',
                'aliases': ['Ginnie Mae', 'GinnieMae'],
            },
            {
                'name': 'Office of Housing',
                'abbreviation': 'HSG',
                'level': 'sub_agency',
                'aliases': ['Office of Housing', 'FHA'],
            },
            {
                'name': 'Office of the Chief Financial Officer',
                'abbreviation': 'OCFO',
                'level': 'office',
                'aliases': ['Office of the Chief Financial Officer (OCFO)', 'OCFO'],
            },
            {
                'name': 'Office of Public Affairs',
                'abbreviation': 'OPA',
                'level': 'office',
                'aliases': ['Office of Public Affairs (OPA)'],
            },
            {
                'name': 'Office of the Chief Human Capital Officer',
                'abbreviation': 'OCHCO',
                'level': 'office',
                'aliases': ['Office of the Chief Human Capital Officer'],
            },
        ],
    },
    {
        'name': 'Department of the Interior',
        'abbreviation': 'DOI',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
        'children': [
            {
                'name': 'U.S. Geological Survey',
                'abbreviation': 'USGS',
                'level': 'sub_agency',
            },
            {
                'name': 'U.S. Fish and Wildlife Service',
                'abbreviation': 'FWS',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of the Solicitor',
                'abbreviation': 'SOL',
                'level': 'office',
            },
            {
                'name': 'Bureau of Reclamation',
                'abbreviation': 'BOR',
                'level': 'sub_agency',
            },
            {
                'name': 'Bureau of Land Management',
                'abbreviation': 'BLM',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of Natural Resources Revenue',
                'abbreviation': 'ONRR',
                'level': 'sub_agency',
            },
            {
                'name': 'Bureau of Safety and Environmental Enforcement',
                'abbreviation': 'BSEE',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of the Secretary',
                'abbreviation': 'OS',
                'level': 'office',
            },
            {
                'name': 'Office of the Chief Information Officer',
                'abbreviation': 'OCIO',
                'level': 'office',
            },
            {
                'name': 'National Park Service',
                'abbreviation': 'NPS',
                'level': 'sub_agency',
            },
            {
                'name': 'Bureau of Trust Funds Administration',
                'abbreviation': 'BTFA',
                'level': 'sub_agency',
            },
            {
                'name': 'Assistant Secretary for Indian Affairs',
                'abbreviation': 'ASIA',
                'level': 'office',
            },
            {
                'name': 'Bureau of Indian Affairs',
                'abbreviation': 'BIA',
                'level': 'sub_agency',
            },
            {
                'name': 'Indian Business Center',
                'abbreviation': 'IBC',
                'level': 'office',
            },
            {
                'name': 'Office of Inspector General',
                'abbreviation': 'OIG',
                'level': 'office',
            },
            {
                'name': 'Bureau of Ocean Energy Management',
                'abbreviation': 'BOEM',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of Surface Mining Reclamation and Enforcement',
                'abbreviation': 'OSMRE',
                'level': 'sub_agency',
            },
        ],
    },
    {
        'name': 'Department of Justice',
        'abbreviation': 'DOJ',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
        'children': [
            {
                'name': 'Federal Bureau of Investigation',
                'abbreviation': 'FBI',
                'level': 'sub_agency',
            },
            {
                'name': 'Drug Enforcement Administration',
                'abbreviation': 'DEA',
                'level': 'sub_agency',
            },
            {
                'name': 'Bureau of Alcohol, Tobacco, Firearms and Explosives',
                'abbreviation': 'ATF',
                'level': 'sub_agency',
            },
            {
                'name': 'Federal Bureau of Prisons',
                'abbreviation': 'FBOP',
                'level': 'sub_agency',
                'aliases': ['BOP'],
            },
            {
                'name': 'U.S. Marshals Service',
                'abbreviation': 'USMS',
                'level': 'sub_agency',
            },
            {
                'name': 'Civil Division',
                'abbreviation': 'CIV',
                'level': 'office',
            },
            {
                'name': 'Tax Division',
                'abbreviation': 'TAX',
                'level': 'office',
            },
            {
                'name': 'Justice Management Division',
                'abbreviation': 'JMD',
                'level': 'office',
                'children': [
                    {
                        'name': 'Organized Crime Drug Enforcement Task Forces',
                        'abbreviation': 'OCDETF',
                        'level': 'office',
                    },
                ],
            },
            {
                'name': 'Antitrust Division',
                'abbreviation': 'ATR',
                'level': 'office',
            },
            {
                'name': 'Office of the Inspector General',
                'abbreviation': 'OIG',
                'level': 'office',
            },
            {
                'name': 'Executive Office for U.S. Attorneys',
                'abbreviation': 'EOUSA',
                'level': 'office',
            },
            {
                'name': 'Executive Office for Immigration Review',
                'abbreviation': 'EOIR',
                'level': 'office',
            },
            {
                'name': 'Civil Rights Division',
                'abbreviation': 'CRT',
                'level': 'office',
            },
            {
                'name': 'Office of Justice Programs',
                'abbreviation': 'OJP',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of the Pardon Attorney',
                'abbreviation': 'PARDON',
                'level': 'office',
                'aliases': ['Office of the Pardon Attorney'],
            },
            {
                'name': 'Environment and Natural Resources Division',
                'abbreviation': 'ENRD',
                'level': 'office',
            },
            {
                'name': 'Criminal Division',
                'abbreviation': 'CRM',
                'level': 'office',
            },
            {
                'name': 'Bureau of Justice Statistics',
                'abbreviation': 'BJS',
                'level': 'sub_agency',
            },
            {
                'name': 'Community Relations Service',
                'abbreviation': 'CRS',
                'level': 'office',
            },
            {
                'name': 'U.S. Trustee Program',
                'abbreviation': 'UST',
                'level': 'office',
                'aliases': ['USTP', 'Department of Justice / USTP'],
            },
            {
                'name': 'Office of Information Policy',
                'abbreviation': 'OIP',
                'level': 'office',
            },
            {
                'name': 'National Drug Intelligence Center',
                'abbreviation': 'NDIC',
                'level': 'office',
            },
            {
                'name': 'Office of Public Affairs',
                'abbreviation': 'PAO',
                'level': 'office',
                'aliases': ['PAO', 'Department of Justice / PAO', 'OPA'],
            },
            {
                'name': 'INTERPOL Washington - U.S. National Central Bureau',
                'abbreviation': 'USNCB',
                'level': 'office',
                'aliases': ['USNCB', 'INTERPOL Washington', 'INTERPOL-USNCB', 'Department of Justice / USNCB'],
            },
            {
                'name': 'Office of Community Oriented Policing Services',
                'abbreviation': 'COPS',
                'level': 'office',
                'aliases': ['COPS', 'COPS Office', 'Department of Justice / COPS'],
            },
            {
                'name': 'Professional Responsibility Advisory Office',
                'abbreviation': 'PRAO',
                'level': 'office',
                'aliases': ['PRAO', 'Department of Justice / PRAO'],
            },
            {
                'name': 'Office of Professional Responsibility',
                'abbreviation': 'OPR',
                'level': 'office',
                'aliases': ['OPR', 'Department of Justice / OPR'],
            },
        ],
    },
    {
        'name': 'Department of Labor',
        'abbreviation': 'DOL',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
        'children': [
            {
                'name': 'Bureau of Labor Statistics',
                'abbreviation': 'BLS',
                'level': 'sub_agency',
            },
            {
                'name': 'Occupational Safety and Health Administration',
                'abbreviation': 'OSHA',
                'level': 'sub_agency',
            },
            {
                'name': 'Employment and Training Administration',
                'abbreviation': 'ETA',
                'level': 'sub_agency',
                'children': [
                    {
                        'name': 'Office of Trade Adjustment Assistance',
                        'abbreviation': 'OTAA',
                        'level': 'office',
                        'aliases': ['OTAA', 'Office of Trade Adjustment Assistance'],
                    },
                ],
            },
            {
                'name': 'Office of the Chief Information Officer',
                'abbreviation': 'OCIO',
                'level': 'office',
            },
            {
                'name': 'Mine Safety and Health Administration',
                'abbreviation': 'MSHA',
                'level': 'sub_agency',
            },
            {
                'name': 'Wage and Hour Division',
                'abbreviation': 'WHD',
                'level': 'office',
            },
            {
                'name': "Veterans' Employment and Training Service",
                'abbreviation': 'VETS',
                'level': 'office',
            },
            {
                'name': "Office of Workers' Compensation Programs",
                'abbreviation': 'OWCP',
                'level': 'office',
            },
            {
                'name': 'Employee Benefits Security Administration',
                'abbreviation': 'EBSA',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of Human Resources',
                'abbreviation': 'OHR',
                'level': 'office',
            },
            {
                'name': 'Office of Disability Employment Policy',
                'abbreviation': 'ODEP',
                'level': 'office',
            },
            {
                'name': 'Chief Evaluation Office',
                'abbreviation': 'CEO',
                'level': 'office',
                'aliases': ['CEO', 'Chief Evaluation Office'],
            },
            {
                'name': "Women's Bureau",
                'abbreviation': 'WB',
                'level': 'sub_agency',
                'aliases': ['WB', "Women's Bureau"],
            },
            {
                'name': 'Bureau of International Labor Affairs',
                'abbreviation': 'ILAB',
                'level': 'sub_agency',
                'aliases': ['ILAB', 'Bureau of International Labor Affairs'],
            },
        ],
    },
    {
        'name': 'Department of State',
        'abbreviation': 'State',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
        'children': [
            {
                'name': 'Bureau of Consular Affairs',
                'abbreviation': 'CA',
                'level': 'sub_agency',
            },
            {
                'name': 'Bureau of Diplomatic Technology',
                'abbreviation': 'DT',
                'level': 'office',
            },
            {
                'name': 'Foreign Service Institute',
                'abbreviation': 'FSI',
                'level': 'sub_agency',
                'aliases': ['NFATC'],
            },
            {
                'name': 'Bureau of Administration',
                'abbreviation': 'MGT',
                'level': 'office',
                'aliases': ['Management'],
            },
            {
                'name': 'Office of U.S. Foreign Assistance',
                'abbreviation': 'F',
                'level': 'office',
                'aliases': ['F/FAO'],
            },
            {
                'name': 'Bureau of Conflict and Stabilization Operations',
                'abbreviation': 'CSO',
                'level': 'office',
            },
            {
                'name': 'Bureau of the Comptroller and Global Financial Services',
                'abbreviation': 'CGFS',
                'level': 'office',
            },
            {
                'name': 'Bureau of Western Hemisphere Affairs',
                'abbreviation': 'WHA',
                'level': 'office',
            },
            {
                'name': 'Bureau of Global Public Affairs',
                'abbreviation': 'GPA',
                'level': 'office',
            },
            {
                'name': 'Bureau of Diplomatic Security',
                'abbreviation': 'DS',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of the Senior Knowledge Strategist',
                'abbreviation': 'A/SKS',
                'level': 'office',
            },
            {
                'name': 'Office of Global Engagement Center',
                'abbreviation': 'R/GEC',
                'level': 'office',
            },
            {
                'name': 'Bureau of Political-Military Affairs',
                'abbreviation': 'PM',
                'level': 'office',
            },
            {
                'name': 'Bureau of Educational and Cultural Affairs',
                'abbreviation': 'ECA',
                'level': 'office',
            },
            {
                'name': 'Bureau of Budget and Planning',
                'abbreviation': 'BP',
                'level': 'office',
            },
            {
                'name': 'Office of Information Resource Management Operations Programs',
                'abbreviation': 'A/PRI',
                'level': 'office',
            },
        ],
    },
    {
        'name': 'Department of Transportation',
        'abbreviation': 'DOT',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
        'children': [
            {
                'name': 'Federal Aviation Administration',
                'abbreviation': 'FAA',
                'level': 'sub_agency',
                'children': [
                    {
                        'name': 'Air Traffic Organization',
                        'abbreviation': 'AJO',
                        'level': 'office',
                    },
                    {
                        'name': 'Aviation Safety',
                        'abbreviation': 'AVS',
                        'level': 'office',
                    },
                    {
                        'name': 'NextGen',
                        'abbreviation': 'ANG',
                        'level': 'office',
                    },
                    {
                        'name': 'Office of the Chief Counsel',
                        'abbreviation': 'AGC',
                        'level': 'office',
                    },
                ],
            },
            {
                'name': 'National Highway Traffic Safety Administration',
                'abbreviation': 'NHTSA',
                'level': 'sub_agency',
            },
            {
                'name': 'Federal Highway Administration',
                'abbreviation': 'FHWA',
                'level': 'sub_agency',
            },
            {
                'name': 'Federal Railroad Administration',
                'abbreviation': 'FRA',
                'level': 'sub_agency',
            },
            {
                'name': 'Federal Transit Administration',
                'abbreviation': 'FTA',
                'level': 'sub_agency',
            },
            {
                'name': 'Maritime Administration',
                'abbreviation': 'MARAD',
                'level': 'sub_agency',
            },
            {
                'name': 'Pipeline and Hazardous Materials Safety Administration',
                'abbreviation': 'PHMSA',
                'level': 'sub_agency',
            },
            {
                'name': 'Federal Motor Carrier Safety Administration',
                'abbreviation': 'FMCSA',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of the Secretary',
                'abbreviation': 'OST',
                'level': 'office',
            },
            {
                'name': 'Office of the Chief Artificial Intelligence Officer',
                'abbreviation': 'CAIO',
                'level': 'office',
            },
            {
                'name': 'National Emerging Technologies Team',
                'abbreviation': 'NETT',
                'level': 'office',
            },
            {
                'name': 'Volpe National Transportation Systems Center',
                'abbreviation': 'Volpe',
                'level': 'sub_agency',
            },
            {
                'name': 'Highly Automated Systems Safety Center of Excellence',
                'abbreviation': 'HASS COE',
                'level': 'office',
                'aliases': ['HASS', 'HASS COE'],
            },
            {
                'name': 'Office of the Assistant Secretary for Research and Technology',
                'abbreviation': 'OST-R',
                'level': 'office',
                'aliases': ['OST-R'],
            },
            {
                'name': 'Office of the Assistant Secretary for Transportation Policy',
                'abbreviation': 'OST-P',
                'level': 'office',
                'aliases': ['OST-P'],
            },
            {
                'name': 'Office of the Assistant Secretary for Administration',
                'abbreviation': 'OST-M',
                'level': 'office',
                'aliases': ['OST-M'],
            },
            {
                'name': 'Office of the Chief Information Officer',
                'abbreviation': 'OCIO',
                'level': 'office',
                'aliases': ['OCIO'],
            },
        ],
    },
    {
        'name': 'Department of the Treasury',
        'abbreviation': 'Treasury',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
        'children': [
            {
                'name': 'Internal Revenue Service',
                'abbreviation': 'IRS',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of the Comptroller of the Currency',
                'abbreviation': 'OCC',
                'level': 'sub_agency',
            },
            {
                'name': 'Bureau of the Fiscal Service',
                'abbreviation': 'BFS',
                'level': 'sub_agency',
            },
            {
                'name': 'Bureau of Engraving and Printing',
                'abbreviation': 'BEP',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of Financial Research',
                'abbreviation': 'OFR',
                'level': 'sub_agency',
            },
            {
                'name': 'Treasury Cybersecurity Service Center',
                'abbreviation': 'TCSC',
                'level': 'office',
            },
            {
                'name': 'Office of Terrorism and Financial Intelligence',
                'abbreviation': 'TFI',
                'level': 'sub_agency',
            },
            {
                'name': 'Financial Crimes Enforcement Network',
                'abbreviation': 'FinCEN',
                'level': 'sub_agency',
            },
            {
                'name': 'U.S. Mint',
                'abbreviation': 'Mint',
                'level': 'sub_agency',
                'aliases': ['United States Mint', 'USM', 'United States Mint (USM)'],
            },
            {
                'name': 'Alcohol and Tobacco Tax and Trade Bureau',
                'abbreviation': 'TTB',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of the General Counsel',
                'abbreviation': 'OGC',
                'level': 'office',
                'aliases': ['General Counsel'],
            },
        ],
    },
    {
        'name': 'Department of Veterans Affairs',
        'abbreviation': 'VA',
        'level': 'department',
        'is_cfo_act_agency': True,
        'is_cabinet_department': True,
        'children': [
            {
                'name': 'Veterans Health Administration',
                'abbreviation': 'VHA',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of Information & Technology',
                'abbreviation': 'OIT',
                'level': 'office',
            },
            {
                'name': 'Veterans Benefits Administration',
                'abbreviation': 'VBA',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of Acquisitions, Logistics, and Construction',
                'abbreviation': 'OALC',
                'level': 'office',
            },
            {
                'name': 'Office of Operations, Security, and Preparedness',
                'abbreviation': 'OSP',
                'level': 'office',
            },
            {
                'name': 'Office of Electronic Health Record Modernization',
                'abbreviation': 'OEHRM',
                'level': 'office',
            },
            {
                'name': 'Veterans Experience Office',
                'abbreviation': 'VEO',
                'level': 'office',
            },
            {
                'name': 'Office of Management',
                'abbreviation': 'OM',
                'level': 'office',
            },
            {
                'name': 'Office of the Executive Secretary',
                'abbreviation': 'OES',
                'level': 'office',
            },
            {
                'name': 'Office of the Deputy Secretary',
                'abbreviation': 'ODS',
                'level': 'office',
                'aliases': ['Office of the Deputy Secretary of VA'],
            },
            {
                'name': 'Office of the Secretary',
                'abbreviation': 'OSVA',
                'level': 'office',
            },
            {
                'name': 'Office of General Counsel',
                'abbreviation': 'OGC',
                'level': 'office',
            },
            {
                'name': 'Office of Accountability and Whistleblower Protection',
                'abbreviation': 'OAWP',
                'level': 'office',
            },
            {
                'name': 'National Cemetery Administration',
                'abbreviation': 'NCA',
                'level': 'sub_agency',
            },
            {
                'name': 'Human Resources Administration',
                'abbreviation': 'HRA',
                'level': 'office',
            },
        ],
    },
    {
        'name': 'Environmental Protection Agency',
        'abbreviation': 'EPA',
        'level': 'independent',
        'is_cfo_act_agency': True,
        'children': [
            {
                'name': 'Office of the Administrator',
                'abbreviation': 'OFA',
                'level': 'office',
                'aliases': ['AO'],
            },
            {
                'name': 'Office of Enforcement and Compliance Assurance',
                'abbreviation': 'OECA',
                'level': 'office',
            },
            {
                'name': 'Office of Air and Radiation',
                'abbreviation': 'OAR',
                'level': 'office',
            },
            {
                'name': 'Office of Mission Support',
                'abbreviation': 'OMS',
                'level': 'office',
            },
            {
                'name': 'Office of Research and Development',
                'abbreviation': 'ORD',
                'level': 'office',
            },
            {
                'name': 'Office of Water',
                'abbreviation': 'OW',
                'level': 'office',
            },
            {
                'name': 'Office of Land and Emergency Management',
                'abbreviation': 'OLEM',
                'level': 'office',
            },
            {
                'name': 'Office of Chemical Safety and Pollution Prevention',
                'abbreviation': 'OCSPP',
                'level': 'office',
            },
            {
                'name': 'Region 8',
                'abbreviation': 'R8',
                'level': 'sub_agency',
                'aliases': ['Region 8', 'EPA Region 8', 'R8'],
            },
            {
                'name': 'Region 1',
                'abbreviation': 'R1',
                'level': 'sub_agency',
                'aliases': ['Region 1', 'EPA Region 1', 'R1'],
            },
        ],
    },
    {
        'name': 'General Services Administration',
        'abbreviation': 'GSA',
        'level': 'independent',
        'is_cfo_act_agency': True,
    },
    {
        'name': 'National Aeronautics and Space Administration',
        'abbreviation': 'NASA',
        'level': 'independent',
        'is_cfo_act_agency': True,
        'children': [
            {
                'name': 'Goddard Space Flight Center',
                'abbreviation': 'GSFC',
                'level': 'sub_agency',
            },
            {
                'name': 'Marshall Space Flight Center',
                'abbreviation': 'MSFC',
                'level': 'sub_agency',
            },
            {
                'name': 'Jet Propulsion Laboratory',
                'abbreviation': 'JPL',
                'level': 'sub_agency',
            },
            {
                'name': 'Langley Research Center',
                'abbreviation': 'LaRC',
                'level': 'sub_agency',
            },
            {
                'name': 'Ames Research Center',
                'abbreviation': 'ARC',
                'level': 'sub_agency',
            },
            {
                'name': 'Johnson Space Center',
                'abbreviation': 'JSC',
                'level': 'sub_agency',
            },
            {
                'name': 'Headquarters',
                'abbreviation': 'HQ',
                'level': 'office',
            },
            {
                'name': 'Glenn Research Center',
                'abbreviation': 'GRC',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of the Chief Safety and Mission Assurance',
                'abbreviation': 'OSMA',
                'level': 'office',
            },
            {
                'name': 'White Sands Test Facility',
                'abbreviation': 'WS',
                'level': 'sub_agency',
            },
            {
                'name': 'Stennis Space Center',
                'abbreviation': 'SSC',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of Protective Services',
                'abbreviation': 'OPS',
                'level': 'office',
            },
            {
                'name': 'Goddard Institute for Space Studies',
                'abbreviation': 'GISS',
                'level': 'office',
            },
            {
                'name': 'Armstrong Flight Research Center',
                'abbreviation': 'AFRC',
                'level': 'sub_agency',
            },
            {
                'name': 'Kennedy Space Center',
                'abbreviation': 'KSC',
                'level': 'sub_agency',
            },
        ],
    },
    {
        'name': 'National Science Foundation',
        'abbreviation': 'NSF',
        'level': 'independent',
        'is_cfo_act_agency': True,
        'children': [
            {
                'name': 'Office of Integrative Activities',
                'abbreviation': 'OIA',
                'level': 'office',
                'children': [
                    {
                        'name': 'Evaluation and Assessment Capability',
                        'abbreviation': 'EAC',
                        'level': 'office',
                        'aliases': ['OIA/EAC', 'OD/OIA/EAC'],
                    },
                ],
            },
            {
                'name': 'Office of the Chief Information Officer',
                'abbreviation': 'OCIO',
                'level': 'office',
            },
            {
                'name': 'Office of Information and Resource Management',
                'abbreviation': 'OIRM',
                'level': 'office',
            },
            {
                'name': 'Office of Legislative and Public Affairs',
                'abbreviation': 'OLPA',
                'level': 'office',
                'aliases': ['OLPA', 'OD/OLPA'],
            },
            {
                'name': 'Office of the General Counsel',
                'abbreviation': 'OGC',
                'level': 'office',
                'aliases': ['OGC'],
            },
            {
                'name': 'Directorate for Biological Sciences',
                'abbreviation': 'BIO',
                'level': 'sub_agency',
                'aliases': ['BIO', '__directorate_BIO__'],
                'children': [
                    {
                        'name': 'Division of Integrative Organismal Systems',
                        'abbreviation': 'IOS',
                        'level': 'office',
                        'aliases': ['BIO/IOS'],
                    },
                ],
            },
            {
                'name': 'Directorate for Engineering',
                'abbreviation': 'ENG',
                'level': 'sub_agency',
                'aliases': ['ENG', '__directorate_ENG__'],
                'children': [
                    {
                        'name': 'Division of Chemical, Bioengineering, Environmental and Transport Systems',
                        'abbreviation': 'CBET',
                        'level': 'office',
                        'aliases': ['ENG/CBET'],
                    },
                ],
            },
            {
                'name': 'Directorate for Computer and Information Science and Engineering',
                'abbreviation': 'CISE',
                'level': 'sub_agency',
                'aliases': ['CISE', '__directorate_CISE__'],
                'children': [
                    {
                        'name': 'Office of the Assistant Director (CISE)',
                        'abbreviation': 'OAD',
                        'level': 'office',
                        'aliases': ['CISE/OAD'],
                    },
                ],
            },
            {
                'name': 'Directorate for STEM Education',
                'abbreviation': 'EDU',
                'level': 'sub_agency',
                'aliases': ['EDU', 'EHR', '__directorate_EDU__'],
                'children': [
                    {
                        'name': 'Division of Research on Learning in Formal and Informal Settings',
                        'abbreviation': 'DRL',
                        'level': 'office',
                        'aliases': ['EDU/DRL', 'EHR/DRL'],
                    },
                ],
            },
            {
                'name': 'Directorate for Social, Behavioral and Economic Sciences',
                'abbreviation': 'SBE',
                'level': 'sub_agency',
                'aliases': ['SBE', '__directorate_SBE__'],
                'children': [
                    {
                        'name': 'National Center for Science and Engineering Statistics',
                        'abbreviation': 'NCSES',
                        'level': 'office',
                        'aliases': ['SBE/NCSES'],
                    },
                ],
            },
            {
                'name': 'Directorate for Technology, Innovation and Partnerships',
                'abbreviation': 'TIP',
                'level': 'sub_agency',
                'aliases': ['TIP', '__directorate_TIP__'],
                'children': [
                    {
                        'name': 'Innovation and Technology Ecosystems - Regional Innovation Engines',
                        'abbreviation': 'ITE-ENGINES',
                        'level': 'office',
                        'aliases': ['TIP-ITE-ENGINES', 'TIP/ITE/ENGINES', 'ITE/ENGINES'],
                    },
                ],
            },
        ],
    },
    {
        'name': 'Nuclear Regulatory Commission',
        'abbreviation': 'NRC',
        'level': 'independent',
        'is_cfo_act_agency': True,
    },
    {
        'name': 'Office of Personnel Management',
        'abbreviation': 'OPM',
        'level': 'independent',
        'is_cfo_act_agency': True,
        'children': [
            {
                'name': 'Office of the Chief Information Officer',
                'abbreviation': 'OCIO',
                'level': 'office',
                'aliases': ['OCIO', 'Chief Information Officer'],
            },
        ],
    },
    {
        'name': 'Small Business Administration',
        'abbreviation': 'SBA',
        'level': 'independent',
        'is_cfo_act_agency': True,
        'children': [
            {
                'name': 'Office of the Chief Information Officer',
                'abbreviation': 'OCIO',
                'level': 'office',
            },
            {
                'name': 'Office of Field Operations',
                'abbreviation': 'OFO',
                'level': 'office',
            },
            {
                'name': 'Office of Capital Access',
                'abbreviation': 'OCA',
                'level': 'office',
            },
            {
                'name': 'Office of Disaster Recovery and Resilience',
                'abbreviation': 'ODRR',
                'level': 'office',
            },
            {
                'name': 'Office of the Chief Financial Officer',
                'abbreviation': 'OCFO',
                'level': 'office',
                'aliases': ['OCFO: Office of the Chief Financial Officer', 'OCFO'],
            },
            {
                'name': 'Office of Advocacy',
                'abbreviation': 'Advocacy',
                'level': 'sub_agency',
                'aliases': ['Advocacy: Office of Advocacy', 'Office of Advocacy'],
            },
            {
                'name': 'Office of Communications and Public Liaison',
                'abbreviation': 'OCPL',
                'level': 'office',
                'aliases': ['OCPL: Office of Communications & Public Liaison', 'OCPL'],
            },
        ],
    },
    {
        'name': 'Social Security Administration',
        'abbreviation': 'SSA',
        'level': 'independent',
        'is_cfo_act_agency': True,
        'children': [
            {
                'name': 'Office of the Chief Information Officer',
                'abbreviation': 'OCIO',
                'level': 'office',
                'aliases': ['Chief Information Officer'],
                'children': [
                    {
                        'name': 'Disability Information Systems',
                        'abbreviation': 'DIS',
                        'level': 'office',
                        'aliases': ['Chief Information Officer, Disability Information Systems'],
                    },
                    {
                        'name': 'Digital Customer Solutions',
                        'abbreviation': 'DCS',
                        'level': 'office',
                        'aliases': ['Chief Information Officer, Digital Customer Solutions'],
                    },
                    {
                        'name': 'System Operations and Hardware Engineering',
                        'abbreviation': 'SOHE',
                        'level': 'office',
                        'aliases': ['Chief Information Officer, System Operations and Hardware Engineering'],
                    },
                ],
            },
            {
                'name': 'Office of Analytics and Improvements',
                'abbreviation': 'OAI',
                'level': 'office',
                'aliases': ['Chief Information Officer, Analytics and Improvements'],
            },
            {
                'name': 'Office of Operations',
                'abbreviation': 'OO',
                'level': 'office',
            },
            {
                'name': 'Office of Human Resources',
                'abbreviation': 'OHR',
                'level': 'office',
                'aliases': ['Human Resources'],
            },
            {
                'name': 'Office of Disability Policy',
                'abbreviation': 'ODP',
                'level': 'office',
                'aliases': ['Law and Policy, Disability Policy'],
            },
        ],
    },
    {
        'name': 'U.S. Agency for International Development',
        'abbreviation': 'USAID',
        'level': 'independent',
        'is_cfo_act_agency': True,
    },
    {
        'name': 'National Archives and Records Administration',
        'abbreviation': 'NARA',
        'level': 'independent',
    },
    {
        'name': 'Securities and Exchange Commission',
        'abbreviation': 'SEC',
        'level': 'independent',
        'children': [
            {
                'name': 'Office of Information Technology',
                'abbreviation': 'OIT',
                'level': 'office',
            },
            {
                'name': 'Division of Examinations',
                'abbreviation': 'EXAMS',
                'level': 'office',
            },
            {
                'name': 'Division of Enforcement',
                'abbreviation': 'ENF',
                'level': 'office',
            },
            {
                'name': 'Division of Economic and Risk Analysis',
                'abbreviation': 'DERA',
                'level': 'office',
            },
            {
                'name': 'Division of Corporation Finance',
                'abbreviation': 'CF',
                'level': 'office',
            },
            {
                'name': 'Division of Trading and Markets',
                'abbreviation': 'TM',
                'level': 'office',
            },
            {
                'name': 'Division of Investment Management',
                'abbreviation': 'IM',
                'level': 'office',
            },
            {
                'name': 'Office of the Chief Data Officer',
                'abbreviation': 'OCDO',
                'level': 'office',
            },
            {
                'name': 'Office of Inspector General',
                'abbreviation': 'OIG',
                'level': 'office',
            },
            {
                'name': 'Office of the General Counsel',
                'abbreviation': 'OGC',
                'level': 'office',
            },
            {
                'name': 'EDGAR Business Office',
                'abbreviation': 'EBO',
                'level': 'office',
                'aliases': ['EDGAR Business Office (EBO)', 'EBO'],
            },
            {
                'name': 'Office of Human Resources',
                'abbreviation': 'OHR',
                'level': 'office',
                'aliases': ['Office of Human Resources (OHR)', 'OHR'],
            },
            {
                'name': 'Strategic Hub for Innovation and Financial Technology',
                'abbreviation': 'FinHub',
                'level': 'office',
                'aliases': ['Strategic Hub for Innocation and Financial Technology (FinHub)', 'Strategic Hub for Innovation and Financial Technology (FinHub)', 'FinHub'],
            },
            {
                'name': 'Office of the Chief Operating Officer',
                'abbreviation': 'OCOO',
                'level': 'office',
                'aliases': ['Office of the Chief Operating Officer (OCOO)', 'OCOO'],
            },
            {
                'name': 'Office of the Secretary',
                'abbreviation': 'OS',
                'level': 'office',
                'aliases': ['Office of the Secretary (OS)', 'OS'],
            },
        ],
    },
    {
        'name': 'Federal Deposit Insurance Corporation',
        'abbreviation': 'FDIC',
        'level': 'independent',
        'children': [
            {
                'name': 'Division of Resolutions and Receiverships',
                'abbreviation': 'DRR',
                'level': 'office',
            },
            {
                'name': 'Division of Finance',
                'abbreviation': 'DOF',
                'level': 'office',
            },
            {
                'name': 'Division of Risk Management Supervision',
                'abbreviation': 'RMS',
                'level': 'office',
            },
            {
                'name': 'Division of Information Technology',
                'abbreviation': 'DIT',
                'level': 'office',
            },
            {
                'name': 'Division of Insurance and Research',
                'abbreviation': 'DIR',
                'level': 'office',
            },
            {
                'name': 'Division of Depositor and Consumer Protection',
                'abbreviation': 'DCP',
                'level': 'office',
            },
            {
                'name': 'Corporate University',
                'abbreviation': 'FDIC-CU',
                'level': 'office',
                'aliases': ['Corporate University'],
            },
            {
                'name': 'Division of Administration',
                'abbreviation': 'DOA',
                'level': 'office',
            },
            {
                'name': 'Division of Complex Institution Supervision and Resolution',
                'abbreviation': 'CISR',
                'level': 'office',
            },
            {
                'name': 'Office of Inspector General',
                'abbreviation': 'OIG',
                'level': 'office',
            },
            {
                'name': 'Office of the General Counsel',
                'abbreviation': 'OGC',
                'level': 'office',
                'aliases': ['Legal Division'],
            },
            {
                'name': 'Chief Information Officer Organization',
                'abbreviation': 'CIOO',
                'level': 'office',
                'aliases': ['Chief Information Officer Organization', 'CIOO'],
            },
            {
                'name': 'Office of Legislative Affairs',
                'abbreviation': 'OLA',
                'level': 'office',
                'aliases': ['Office of Legislative Affairs'],
            },
            {
                'name': 'Office of Communications',
                'abbreviation': 'OCOM',
                'level': 'office',
                'aliases': ['Office of Communications'],
            },
        ],
    },
    {
        'name': 'Federal Reserve Board',
        'abbreviation': 'FRB',
        'level': 'independent',
        'aliases': ['Federal Reserve System'],
        'children': [
            {
                'name': 'Division of Supervision and Regulation',
                'abbreviation': 'S&R',
                'level': 'office',
            },
            {
                'name': 'Division of Information Technology',
                'abbreviation': 'IT',
                'level': 'office',
            },
            {
                'name': 'Division of Reserve Bank Operations and Payment Systems',
                'abbreviation': 'RBOPS',
                'level': 'office',
            },
            {
                'name': 'Division of Research and Statistics',
                'abbreviation': 'R&S',
                'level': 'office',
            },
            {
                'name': 'Division of Monetary Affairs',
                'abbreviation': 'MA',
                'level': 'office',
            },
            {
                'name': 'Division of Financial Stability',
                'abbreviation': 'FS',
                'level': 'office',
            },
            {
                'name': 'Office of the Secretary',
                'abbreviation': 'OS',
                'level': 'office',
                'aliases': ['Office of the Secretary'],
            },
            {
                'name': 'Office of Inspector General',
                'abbreviation': 'OIG',
                'level': 'office',
                'aliases': ['Office of the Inspector General', 'OIG'],
            },
            {
                'name': 'Division of Consumer and Community Affairs',
                'abbreviation': 'DCCA',
                'level': 'office',
                'aliases': ['Division of Consumer and Community Affairs', 'DCCA'],
            },
            {
                'name': 'Division of Management',
                'abbreviation': 'MGT',
                'level': 'office',
                'aliases': ['Division of Management'],
            },
        ],
    },
    {
        'name': 'Federal Housing Finance Agency',
        'abbreviation': 'FHFA',
        'level': 'independent',
        'children': [
            {
                'name': 'Office of the Chief Information Officer',
                'abbreviation': 'OCIO',
                'level': 'office',
            },
            {
                'name': 'Division of Housing Mission and Goals',
                'abbreviation': 'DHMG',
                'level': 'office',
            },
            {
                'name': 'Office of the General Counsel',
                'abbreviation': 'OGC',
                'level': 'office',
                'aliases': ['OGC'],
            },
            {
                'name': 'Office of the Chief Operating Officer',
                'abbreviation': 'OCOO',
                'level': 'office',
                'aliases': ['OCOO'],
            },
            {
                'name': 'Division of Bank Regulation',
                'abbreviation': 'DBR',
                'level': 'office',
                'aliases': ['DBR'],
            },
            {
                'name': 'Office of the Chief Financial Officer',
                'abbreviation': 'OCFO',
                'level': 'office',
                'aliases': ['OCFO'],
            },
        ],
    },
    {
        'name': 'Federal Trade Commission',
        'abbreviation': 'FTC',
        'level': 'independent',
        'children': [
            {
                'name': 'Bureau of Consumer Protection',
                'abbreviation': 'BCP',
                'level': 'sub_agency',
                'aliases': ['BCP/DCRO'],
            },
            {
                'name': 'Bureau of Competition',
                'abbreviation': 'BC',
                'level': 'sub_agency',
            },
            {
                'name': 'Office of the Chief Information Officer',
                'abbreviation': 'OCIO',
                'level': 'office',
            },
        ],
    },
    {
        'name': 'Federal Communications Commission',
        'abbreviation': 'FCC',
        'level': 'independent',
    },
    {
        'name': 'Federal Energy Regulatory Commission',
        'abbreviation': 'FERC',
        'level': 'independent',
    },
    {
        'name': 'Tennessee Valley Authority',
        'abbreviation': 'TVA',
        'level': 'independent',
        'children': [
            {
                'name': 'Information Technology',
                'abbreviation': 'IT',
                'level': 'office',
                'children': [
                    {
                        'name': 'Network',
                        'abbreviation': 'Network',
                        'level': 'office',
                        'aliases': ['Network'],
                    },
                ],
            },
            {
                'name': 'Commercial Energy Solutions',
                'abbreviation': 'CES',
                'level': 'office',
            },
            {
                'name': 'Power Operations',
                'abbreviation': 'PO',
                'level': 'office',
                'children': [
                    {
                        'name': 'Generation Projects & Fleet Services',
                        'abbreviation': 'GPFS',
                        'level': 'office',
                        'aliases': ['Generation Projects & Fleet Services', 'Generation Projects and Fleet Services'],
                    },
                    {
                        'name': 'Generation Projects & Fleet Strategy',
                        'abbreviation': 'GPFStr',
                        'level': 'office',
                        'aliases': ['Generation Projects & Fleet Strategy', 'Generation Projects and Fleet Strategy'],
                    },
                    {
                        'name': 'Transmission',
                        'abbreviation': 'TX',
                        'level': 'office',
                        'aliases': ['Transmission', 'Transmission and Power Supply'],
                    },
                    {
                        'name': 'Generation',
                        'abbreviation': 'GEN',
                        'level': 'office',
                        'aliases': ['Generation', 'Coal Gas and Hydro Generation'],
                    },
                    {
                        'name': 'Nuclear',
                        'abbreviation': 'NUC',
                        'level': 'office',
                        'aliases': ['Nuclear', 'Nuclear Operations'],
                    },
                    {
                        'name': 'Right of Way',
                        'abbreviation': 'ROW',
                        'level': 'component',
                        'aliases': ['Right of Way', 'Transmission Right of Way'],
                    },
                    {
                        'name': 'Monitoring & Diagnostics Management',
                        'abbreviation': 'MDM',
                        'level': 'office',
                        'aliases': ['Monitoring Diagnostics Management', 'Monitoring & Diagnostics Management', 'M&D'],
                    },
                    {
                        'name': 'Transmission System Support',
                        'abbreviation': 'TSS',
                        'level': 'component',
                        'aliases': ['Transmission System Support'],
                    },
                ],
            },
            {
                'name': 'External Relations',
                'abbreviation': 'ER',
                'level': 'office',
                'aliases': ['External Communications'],
            },
            {
                'name': 'Enterprise Analytics & Innovation',
                'abbreviation': 'EAI',
                'level': 'sub_agency',
                'aliases': ['Enterprise Analytics & Innovation', 'Enterprise Analytics and Innovation'],
            },
            {
                'name': 'Enterprise Planning',
                'abbreviation': 'EP',
                'level': 'sub_agency',
                'aliases': ['Enterprise Planning'],
            },
            {
                'name': 'Supply Chain',
                'abbreviation': 'SC',
                'level': 'sub_agency',
                'aliases': ['Supply Chain'],
            },
            {
                'name': 'Innovation & Research',
                'abbreviation': 'I&R',
                'level': 'sub_agency',
                'aliases': ['Innovation & Research', 'Innovation and Research', 'Technology Innovation'],
            },
            {
                'name': 'Geographic Information Systems',
                'abbreviation': 'GIS',
                'level': 'office',
                'aliases': ['GIS'],
            },
            {
                'name': 'Workforce Development',
                'abbreviation': 'WFD',
                'level': 'office',
                'aliases': ['Workforce Development'],
            },
            {
                'name': 'River & Fleet Management Services',
                'abbreviation': 'RFMS',
                'level': 'sub_agency',
                'aliases': ['Riverfleet Management Services', 'River Fleet Management Services', 'River & Fleet Management Services'],
            },
            {
                'name': 'Office of General Counsel',
                'abbreviation': 'OGC',
                'level': 'office',
                'aliases': ['Office of General Counsel', 'General Counsel'],
            },
            {
                'name': 'Safety & Shared Services',
                'abbreviation': 'SSS',
                'level': 'sub_agency',
                'aliases': ['Safety & Shared Services', 'Safety and Shared Services'],
            },
            {
                'name': 'River Management',
                'abbreviation': 'RM',
                'level': 'sub_agency',
                'aliases': ['River Management', 'Integrated River System Management', 'River Operations'],
            },
            {
                'name': 'Economic Development',
                'abbreviation': 'ED',
                'level': 'sub_agency',
                'aliases': ['Economic Development', 'TVA Economic Development'],
            },
        ],
    },
    {
        'name': 'Commodity Futures Trading Commission',
        'abbreviation': 'CFTC',
        'level': 'independent',
        'children': [
            {
                'name': 'Division of Data',
                'abbreviation': 'DOD',
                'level': 'sub_agency',
                'aliases': ['DOD', 'Division of Data'],
            },
            {
                'name': 'Division of Clearing and Risk',
                'abbreviation': 'DCR',
                'level': 'sub_agency',
                'aliases': ['DCR', 'Division of Clearing and Risk'],
            },
            {
                'name': 'Market Participants Division',
                'abbreviation': 'MPD',
                'level': 'sub_agency',
                'aliases': ['MPD', 'Market Participants Division'],
            },
        ],
    },
    {
        'name': 'Consumer Financial Protection Bureau',
        'abbreviation': 'CFPB',
        'level': 'independent',
    },
    {
        'name': 'Consumer Product Safety Commission',
        'abbreviation': 'CPSC',
        'level': 'independent',
    },
    {
        'name': 'Equal Employment Opportunity Commission',
        'abbreviation': 'EEOC',
        'level': 'independent',
    },
    {
        'name': 'Export-Import Bank',
        'abbreviation': 'EXIM',
        'level': 'independent',
    },
    {
        'name': 'Federal Labor Relations Authority',
        'abbreviation': 'FLRA',
        'level': 'independent',
    },
    {
        'name': 'Government Accountability Office',
        'abbreviation': 'GAO',
        'level': 'independent',
    },
    {
        'name': 'Government Publishing Office',
        'abbreviation': 'GPO',
        'level': 'independent',
    },
    {
        'name': 'Merit Systems Protection Board',
        'abbreviation': 'MSPB',
        'level': 'independent',
    },
    {
        'name': 'National Credit Union Administration',
        'abbreviation': 'NCUA',
        'level': 'independent',
    },
    {
        'name': 'National Endowment for the Humanities',
        'abbreviation': 'NEH',
        'level': 'independent',
    },
    {
        'name': 'National Labor Relations Board',
        'abbreviation': 'NLRB',
        'level': 'independent',
    },
    {
        'name': 'National Mediation Board',
        'abbreviation': 'NMB',
        'level': 'independent',
    },
    {
        'name': 'National Transportation Safety Board',
        'abbreviation': 'NTSB',
        'level': 'independent',
    },
    {
        'name': 'Office of the Director of National Intelligence',
        'abbreviation': 'ODNI',
        'level': 'independent',
    },
    {
        'name': 'Office of Special Counsel',
        'abbreviation': 'OSC',
        'level': 'independent',
    },
    {
        'name': 'Peace Corps',
        'abbreviation': 'PeaceCorps',
        'level': 'independent',
        'aliases': ['Peace Corps'],
    },
    {
        'name': 'Pension Benefit Guaranty Corporation',
        'abbreviation': 'PBGC',
        'level': 'independent',
    },
    {
        'name': 'Postal Regulatory Commission',
        'abbreviation': 'PRC',
        'level': 'independent',
    },
    {
        'name': 'Presidio Trust',
        'abbreviation': 'PT',
        'level': 'independent',
    },
    {
        'name': 'Court Services and Offender Supervision Agency',
        'abbreviation': 'CSOSA',
        'level': 'independent',
    },
    {
        'name': 'Election Assistance Commission',
        'abbreviation': 'EAC',
        'level': 'independent',
    },
    {
        'name': 'Federal Retirement Thrift Investment Board',
        'abbreviation': 'FRTIB',
        'level': 'independent',
    },
    {
        'name': 'U.S. Agency for Global Media',
        'abbreviation': 'USAGM',
        'level': 'independent',
    },
    {
        'name': 'U.S. Commission on Civil Rights',
        'abbreviation': 'USCCR',
        'level': 'independent',
    },
    {
        'name': 'U.S. International Trade Commission',
        'abbreviation': 'USITC',
        'level': 'independent',
    },
    {
        'name': 'U.S. Trade and Development Agency',
        'abbreviation': 'USTDA',
        'level': 'independent',
    },
]
