"""Generate a remediation before/after report from baseline JSON snapshots.

Two modes:

1. Diff mode (default):
       python scripts/generate_remediation_report.py \
         --before audit/baselines/2026-04-12-pre-remediation.json \
         --after  audit/baselines/2026-04-12-post-remediation.json \
         --out    audit/remediation-report.md

   Reads two snapshots and writes a Markdown report grouped by issue class
   (id traceability, LLM false positives, vendor/custom, product mapping,
   scope, field fullness) showing before -> after -> delta.

   If --after does not exist the script prints a notice and exits 0
   (non-fatal; the post baseline is captured at end of Phase 2).

2. Snapshot mode:
       python scripts/generate_remediation_report.py \
         --snapshot audit/baselines/2026-04-12-post-remediation.json

   Reads the live SQLite DB read-only and writes a fresh JSON file using
   the same schema as the pre-remediation baseline. Coordinator runs this
   after Phase 2 lands.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = REPO_ROOT / "data" / "federal_ai_inventory_2025.db"


# -----------------------------------------------------------------------------
# Issue-class grouping. Each entry: (section title, [(label, baseline JSON key)])
# -----------------------------------------------------------------------------

ISSUE_GROUPS: List[Tuple[str, List[Tuple[str, str]]]] = [
    (
        "Row counts and ingest integrity",
        [
            ("use_cases total", "use_cases_total"),
            ("consolidated_use_cases total", "consolidated_use_cases_total"),
        ],
    ),
    (
        "ID traceability",
        [
            ("use_cases with NULL use_case_id", "use_case_id_null"),
            (
                "NULL use_case_id recoverable from raw_json",
                "use_case_id_recoverable_from_raw_json",
            ),
        ],
    ),
    (
        "LLM vs non-LLM classification",
        [
            ("Confirmed LLM false positives", "llm_false_positives_confirmed"),
            (
                "LLM-tagged with blank ai_classification",
                "llm_tagged_with_blank_classification",
            ),
        ],
    ),
    (
        "Vendor product vs custom system",
        [
            (
                "custom_system rows with vendor_name populated",
                "custom_system_with_vendor_name",
            ),
        ],
    ),
    (
        "Product mapping and alias quality",
        [
            ("use_cases rows with NULL product_id", "product_id_null_on_use_cases"),
        ],
    ),
    (
        "Scope and maturity consistency",
        [
            ("enterprise_wide consolidated rows", "enterprise_wide_consolidated"),
        ],
    ),
    (
        "Field fullness and tag coarseness",
        [
            ("architecture_type='unknown' rows", "architecture_unknown"),
            ("rag_pipeline-tagged rows", "rag_pipeline_tagged"),
            ("agentic_workflow-tagged rows", "agentic_workflow_tagged"),
        ],
    ),
]


# -----------------------------------------------------------------------------
# Snapshot mode: query DB and write a baseline JSON
# -----------------------------------------------------------------------------

def _scalar(conn: sqlite3.Connection, sql: str, params: Tuple = ()) -> int:
    return conn.execute(sql, params).fetchone()[0]


def collect_snapshot(snapshot_date: str) -> Dict[str, Any]:
    if not DB_PATH.exists():
        print(f"ERROR: DB not found at {DB_PATH}", file=sys.stderr)
        sys.exit(2)

    conn = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    try:
        snap: Dict[str, Any] = {
            "snapshot_date": snapshot_date,
            "notes": (
                "Auto-generated by scripts/generate_remediation_report.py --snapshot. "
                "Schema mirrors audit/baselines/2026-04-12-pre-remediation.json."
            ),
        }
        snap["use_cases_total"] = _scalar(conn, "SELECT COUNT(*) FROM use_cases")
        snap["consolidated_use_cases_total"] = _scalar(
            conn, "SELECT COUNT(*) FROM consolidated_use_cases"
        )
        snap["use_case_id_null"] = _scalar(
            conn,
            "SELECT COUNT(*) FROM use_cases WHERE use_case_id IS NULL OR TRIM(use_case_id)=''",
        )
        snap["use_case_id_recoverable_from_raw_json"] = _scalar(
            conn,
            """
            SELECT COUNT(*) FROM use_cases
            WHERE (use_case_id IS NULL OR TRIM(use_case_id)='')
              AND raw_json IS NOT NULL
              AND (raw_json LIKE '%"Use Case ID"%'
                   OR raw_json LIKE '%"use_case_id"%'
                   OR raw_json LIKE '%"Use Case Identifier"%'
                   OR raw_json LIKE '%"ID"%')
            """,
        )
        # Canonical LLM false-positive definition: is_general_llm_access=1
        # AND source ai_classification names a non-LLM category
        # (Classical/Predictive ML or Computer Vision). Matches the pre-remediation
        # baseline count of 88; do not change this predicate without updating
        # audit/baselines/2026-04-12-pre-remediation.json.
        snap["llm_false_positives_confirmed"] = _scalar(
            conn,
            """
            SELECT COUNT(*) FROM use_cases u
            JOIN use_case_tags t ON t.use_case_id = u.id
            WHERE t.is_general_llm_access = 1
              AND (u.ai_classification LIKE '%Classical%'
                   OR u.ai_classification LIKE '%Predictive%'
                   OR u.ai_classification LIKE '%Computer Vision%')
            """,
        )
        cml = _scalar(
            conn,
            """
            SELECT COUNT(*) FROM use_cases u
            JOIN use_case_tags t ON t.use_case_id = u.id
            WHERE t.is_general_llm_access = 1
              AND (u.ai_classification LIKE '%Classical%'
                   OR u.ai_classification LIKE '%Predictive%')
            """,
        )
        cv = _scalar(
            conn,
            """
            SELECT COUNT(*) FROM use_cases u
            JOIN use_case_tags t ON t.use_case_id = u.id
            WHERE t.is_general_llm_access = 1
              AND u.ai_classification LIKE '%Computer Vision%'
            """,
        )
        snap["llm_false_positives_breakdown"] = {
            "classical_ml": cml,
            "computer_vision": cv,
        }
        snap["llm_tagged_with_blank_classification"] = _scalar(
            conn,
            """
            SELECT COUNT(*) FROM use_cases u
            JOIN use_case_tags t ON t.use_case_id = u.id
            WHERE (t.ai_sophistication = 'general_llm'
                   OR t.is_general_llm_access = 1
                   OR t.is_generative_ai = 1)
              AND (u.ai_classification IS NULL OR TRIM(u.ai_classification) = '')
            """,
        )
        snap["custom_system_with_vendor_name"] = _scalar(
            conn,
            """
            SELECT COUNT(*) FROM use_cases u
            JOIN use_case_tags t ON t.use_case_id = u.id
            WHERE t.entry_type = 'custom_system'
              AND u.vendor_name IS NOT NULL
              AND TRIM(u.vendor_name) <> ''
            """,
        )
        # Per-agency top10 for custom_system_with_vendor. Keyed by abbreviation
        # (HHS, DOJ, ...) to match the pre-remediation baseline schema.
        rows = conn.execute(
            """
            SELECT a.abbreviation, COUNT(*) AS n
            FROM use_cases u
            JOIN use_case_tags t ON t.use_case_id = u.id
            JOIN agencies a ON a.id = u.agency_id
            WHERE t.entry_type = 'custom_system'
              AND u.vendor_name IS NOT NULL
              AND TRIM(u.vendor_name) <> ''
            GROUP BY a.abbreviation
            ORDER BY n DESC
            LIMIT 10
            """
        ).fetchall()
        snap["custom_system_by_agency_top10"] = {abbr: n for abbr, n in rows}

        snap["enterprise_wide_consolidated"] = _scalar(
            conn,
            """
            SELECT COUNT(*) FROM use_case_tags t
            JOIN consolidated_use_cases c ON c.id = t.consolidated_use_case_id
            WHERE t.deployment_scope = 'enterprise_wide'
            """,
        )
        ew_y = _scalar(
            conn,
            """
            SELECT COUNT(*) FROM use_case_tags t
            JOIN consolidated_use_cases c ON c.id = t.consolidated_use_case_id
            WHERE t.deployment_scope = 'enterprise_wide' AND c.agency_uses = 'Y'
            """,
        )
        ew_n = _scalar(
            conn,
            """
            SELECT COUNT(*) FROM use_case_tags t
            JOIN consolidated_use_cases c ON c.id = t.consolidated_use_case_id
            WHERE t.deployment_scope = 'enterprise_wide' AND c.agency_uses = 'N'
            """,
        )
        ew_null = _scalar(
            conn,
            """
            SELECT COUNT(*) FROM use_case_tags t
            JOIN consolidated_use_cases c ON c.id = t.consolidated_use_case_id
            WHERE t.deployment_scope = 'enterprise_wide'
              AND (c.agency_uses IS NULL OR TRIM(c.agency_uses) = '')
            """,
        )
        snap["enterprise_wide_agency_uses_split"] = {
            "Y": ew_y,
            "N": ew_n,
            "NULL": ew_null,
        }
        snap["rag_pipeline_tagged"] = _scalar(
            conn,
            "SELECT COUNT(*) FROM use_case_tags WHERE architecture_type = 'rag_pipeline'",
        )
        snap["agentic_workflow_tagged"] = _scalar(
            conn,
            "SELECT COUNT(*) FROM use_case_tags WHERE architecture_type = 'agentic_workflow'",
        )
        snap["architecture_unknown"] = _scalar(
            conn,
            "SELECT COUNT(*) FROM use_case_tags WHERE architecture_type = 'unknown'",
        )
        snap["product_id_null_on_use_cases"] = _scalar(
            conn,
            "SELECT COUNT(*) FROM use_cases WHERE product_id IS NULL",
        )
        return snap
    finally:
        conn.close()


def write_snapshot(out_path: Path, snapshot_date: str) -> None:
    snap = collect_snapshot(snapshot_date)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(snap, indent=2) + "\n")
    print(f"Wrote snapshot to {out_path}")


# -----------------------------------------------------------------------------
# Diff mode: compare two baselines and emit Markdown
# -----------------------------------------------------------------------------

def _format_value(v: Any) -> str:
    if v is None:
        return "n/a"
    return str(v)


def _format_delta(before: Any, after: Any) -> str:
    if isinstance(before, (int, float)) and isinstance(after, (int, float)):
        delta = after - before
        if delta == 0:
            return "0"
        sign = "+" if delta > 0 else ""
        if before:
            pct = (delta / before) * 100
            return f"{sign}{delta} ({sign}{pct:.1f}%)"
        return f"{sign}{delta}"
    return "n/a"


def render_report(before: Dict[str, Any], after: Dict[str, Any]) -> str:
    lines: List[str] = []
    lines.append("# Remediation Report")
    lines.append("")
    lines.append(
        f"- Before snapshot: `{before.get('snapshot_date', 'unknown')}`"
    )
    lines.append(f"- After snapshot:  `{after.get('snapshot_date', 'unknown')}`")
    lines.append("")
    lines.append(
        "Generated by `scripts/generate_remediation_report.py`. Counts come from "
        "matching keys in the two baseline JSON files."
    )
    lines.append("")

    for section_title, items in ISSUE_GROUPS:
        lines.append(f"## {section_title}")
        lines.append("")
        lines.append("| Metric | Before | After | Delta |")
        lines.append("| --- | ---: | ---: | ---: |")
        for label, key in items:
            b = before.get(key)
            a = after.get(key)
            lines.append(
                f"| {label} | {_format_value(b)} | {_format_value(a)} | "
                f"{_format_delta(b, a)} |"
            )
        lines.append("")

    # Show the LLM breakdown sub-table when present.
    b_break = before.get("llm_false_positives_breakdown") or {}
    a_break = after.get("llm_false_positives_breakdown") or {}
    if b_break or a_break:
        lines.append("### LLM false-positive breakdown")
        lines.append("")
        lines.append("| Sub-class | Before | After | Delta |")
        lines.append("| --- | ---: | ---: | ---: |")
        for sub in sorted(set(b_break) | set(a_break)):
            b = b_break.get(sub)
            a = a_break.get(sub)
            lines.append(
                f"| {sub} | {_format_value(b)} | {_format_value(a)} | "
                f"{_format_delta(b, a)} |"
            )
        lines.append("")

    return "\n".join(lines) + "\n"


def diff_mode(before_path: Path, after_path: Path, out_path: Path) -> int:
    if not before_path.exists():
        print(f"ERROR: --before file not found: {before_path}", file=sys.stderr)
        return 2
    if not after_path.exists():
        print(
            f"post-remediation baseline not yet written ({after_path} missing); "
            "skipping report generation",
        )
        return 0
    before = json.loads(before_path.read_text())
    after = json.loads(after_path.read_text())
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_report(before, after))
    print(f"Wrote report to {out_path}")
    return 0


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------

def main(argv: List[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    p.add_argument("--before", type=Path, help="path to pre-remediation baseline JSON")
    p.add_argument("--after", type=Path, help="path to post-remediation baseline JSON")
    p.add_argument(
        "--out",
        type=Path,
        default=REPO_ROOT / "audit" / "remediation-report.md",
        help="path to write the Markdown report",
    )
    p.add_argument(
        "--snapshot",
        type=Path,
        help=(
            "Snapshot mode: read live DB and write a fresh baseline JSON to "
            "this path, using the same schema as the pre-remediation baseline."
        ),
    )
    p.add_argument(
        "--snapshot-date",
        default=None,
        help="Snapshot date label written into the JSON (defaults to today UTC).",
    )
    args = p.parse_args(argv)

    if args.snapshot:
        from datetime import datetime, timezone
        date = args.snapshot_date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
        write_snapshot(args.snapshot, date)
        return 0

    if not args.before or not args.after:
        p.error("--before and --after are required in diff mode (or pass --snapshot)")
    return diff_mode(args.before, args.after, args.out)


if __name__ == "__main__":
    sys.exit(main())
